import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { createInterface } from "node:readline";
import type { ParsedArgs } from "../args.js";
import { flagAsBool, flagAsInt, flagAsString } from "../args.js";
import { bold, cyan, dim, gray, green, red, yellow } from "../colors.js";
import { Output } from "../output.js";
import { withSpinner } from "../spinner.js";
import { EXTENSION_ID, installAndVerify, isEditorClient } from "./extensions.js";
import { buildServerSpec, type ClientDef, CLIENTS, findClient } from "./mcp-clients.js";
import { writeInit } from "./mcp-init.js";
import { runMcpSeed } from "./mcp-seed.js";
import {
  dockerFixHint,
  dockerState,
  gitAvailable,
  MIN_NODE_MAJOR,
  nodeMeetsMinimum,
} from "./preflight.js";
import { buildProviderEnv, type ProviderConfig, PROVIDERS } from "./providers.js";
import { discoverRepos, resolveRepoIdentity, type RepoIdentity } from "./repo.js";

const STATE_DIR = resolve(homedir(), ".statewave/quickstart");
const COMPOSE_PATH = resolve(STATE_DIR, "docker-compose.yml");
const PROJECT_NAME = "statewave-quickstart";

export interface ComposeOptions {
  apiPort: number;
  adminPort: number;
  includeAdmin: boolean;
  version?: string;
  adminVersion?: string;
}

/**
 * A self-contained compose file pinned to the published images — no local
 * checkout required. It mirrors the project's own compose but drops the
 * `build:` and the `../statewave-docs` volume (which assume a sibling repo) so
 * it runs anywhere. Debug mode means zero API keys and the admin needs no
 * password — a fresh `up -d` just works.
 */
export function renderComposeFile(opts: ComposeOptions): string {
  const tag = opts.version ?? "latest";
  const adminTag = opts.adminVersion ?? "latest";
  const admin = opts.includeAdmin
    ? `  admin:
    image: statewavedev/statewave-admin:${adminTag}
    ports:
      - "${opts.adminPort}:8080"
    environment:
      STATEWAVE_API_URL: http://api:8100
      STATEWAVE_API_KEY: dev-local-placeholder
      NODE_ENV: production
      ADMIN_AUTH_DISABLED: "true"
    depends_on:
      api:
        condition: service_started
`
    : "";
  return `# Generated by \`statewave-connectors quickstart\`. Safe to delete.
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: statewave
      POSTGRES_PASSWORD: statewave
      POSTGRES_DB: statewave
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statewave"]
      interval: 2s
      timeout: 5s
      retries: 15
  api:
    image: statewavedev/statewave:${tag}
    ports:
      - "${opts.apiPort}:8100"
    environment:
      STATEWAVE_DATABASE_URL: postgresql+asyncpg://statewave:statewave@db:5432/statewave
      STATEWAVE_DEBUG: "true"
      STATEWAVE_BOOTSTRAP_DOCS_PACK: "false"
      # LLM compiler + embeddings are off unless a key is supplied. These read
      # from the environment passed to \`docker compose up\` (so the secret is
      # never written to this file); they fall back to the keyless defaults.
      STATEWAVE_COMPILER_TYPE: \${STATEWAVE_COMPILER_TYPE:-heuristic}
      STATEWAVE_EMBEDDING_PROVIDER: \${STATEWAVE_EMBEDDING_PROVIDER:-stub}
      STATEWAVE_LITELLM_API_KEY: \${STATEWAVE_LITELLM_API_KEY:-}
      STATEWAVE_LITELLM_MODEL: \${STATEWAVE_LITELLM_MODEL:-gpt-4o-mini}
      STATEWAVE_LITELLM_EMBEDDING_MODEL: \${STATEWAVE_LITELLM_EMBEDDING_MODEL:-text-embedding-3-small}
    depends_on:
      db:
        condition: service_healthy
${admin}volumes:
  pgdata:
`;
}

/**
 * Server env that turns on the LLM compiler + semantic embeddings when a key is
 * supplied. Empty when there's no key — the server then uses the keyless
 * heuristic compiler + stub embeddings. The key is passed to `docker compose`
 * via the environment, never written to the compose file.
 */
export function llmEnv(apiKey?: string, model?: string): Record<string, string> {
  if (!apiKey) return {};
  const env: Record<string, string> = {
    STATEWAVE_COMPILER_TYPE: "llm",
    STATEWAVE_EMBEDDING_PROVIDER: "litellm",
    STATEWAVE_LITELLM_API_KEY: apiKey,
  };
  if (model) env.STATEWAVE_LITELLM_MODEL = model;
  return env;
}

export async function checkHealth(baseUrl: string, fetchImpl: typeof fetch = fetch): Promise<boolean> {
  try {
    const res = await fetchImpl(`${baseUrl.replace(/\/+$/, "")}/healthz`, { method: "GET" });
    return res.ok;
  } catch {
    return false;
  }
}

export async function waitForHealth(
  baseUrl: string,
  opts: { timeoutMs: number; intervalMs: number; fetchImpl?: typeof fetch; onTick?: () => void },
): Promise<boolean> {
  const deadline = Date.now() + opts.timeoutMs;
  while (Date.now() < deadline) {
    if (await checkHealth(baseUrl, opts.fetchImpl)) return true;
    opts.onTick?.();
    await new Promise((r) => setTimeout(r, opts.intervalMs));
  }
  return checkHealth(baseUrl, opts.fetchImpl);
}

/** Resolve the absolute path to the mcp-server bin this CLI ships with. */
function resolveLocalServerBin(): string | undefined {
  try {
    const req = createRequire(import.meta.url);
    const pkgPath = req.resolve("@statewavedev/mcp-server/package.json");
    const pkg = req("@statewavedev/mcp-server/package.json") as { bin?: string | Record<string, string> };
    const binRel =
      typeof pkg.bin === "string" ? pkg.bin : pkg.bin ? Object.values(pkg.bin)[0] : undefined;
    return binRel ? resolve(dirname(pkgPath), binRel) : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Ensure Docker is usable, with OS-specific guidance per failure mode. Offers an
 * interactive retry (and "open Docker Desktop") only for a stopped daemon — the
 * other states need a real install or permission change first. Returns false
 * when Docker can't be made ready.
 */
async function ensureDockerReady(out: Output): Promise<boolean> {
  for (;;) {
    const state = dockerState();
    if (state === "ok") return true;
    out.error(
      state === "no-cli"
        ? "Docker is required to start a local Statewave server"
        : state === "no-compose"
          ? "Docker Compose v2 (`docker compose`) is required"
          : state === "daemon-down"
            ? "Docker is installed but the daemon isn't running"
            : "Permission denied talking to the Docker daemon",
    );
    for (const line of dockerFixHint(state)) out.log(dim(`  ${line}`));
    if (state !== "daemon-down" || !process.stdin.isTTY || out.isJson()) {
      out.log(dim("  Or point --statewave-url at an already-running server."));
      return false;
    }
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const ans = (
      await new Promise<string>((res) =>
        rl.question(`  ${dim("[Enter = retry, 'o' = open Docker Desktop & retry, 'x' = exit]")}: `, res),
      )
    )
      .trim()
      .toLowerCase();
    rl.close();
    if (ans === "x") return false;
    if (ans === "o" && process.platform === "darwin") {
      try {
        execFileSync("open", ["-a", "Docker"], { stdio: "ignore" });
        out.log(dim("  Opening Docker Desktop… giving it a moment before retrying."));
      } catch {
        // open failed — fall through to a plain retry
      }
    }
    await new Promise((r) => setTimeout(r, ans === "o" ? 8000 : 1500));
  }
}

/** First absolute path for `bin` on the PATH, or undefined. Cross-platform. */
function resolveOnPath(bin: string): string | undefined {
  const sep = process.platform === "win32" ? ";" : ":";
  const names = process.platform === "win32" ? [`${bin}.exe`, `${bin}.cmd`, bin] : [bin];
  for (const d of (process.env.PATH ?? "").split(sep)) {
    if (!d) continue;
    for (const n of names) {
      const p = join(d, n);
      if (existsSync(p)) return p;
    }
  }
  return undefined;
}

function onPath(bin: string): boolean {
  return resolveOnPath(bin) !== undefined;
}

// Best-effort "is this client installed?" — a config dir, an app bundle, or the
// binary on PATH. Used to pick sensible defaults; --client / --all always win.
const CLIENT_DETECT: Record<string, () => boolean> = {
  "claude-desktop": () =>
    existsSync(resolve(homedir(), "Library/Application Support/Claude")) ||
    existsSync(resolve(homedir(), ".config/Claude")) ||
    (!!process.env.APPDATA && existsSync(join(process.env.APPDATA, "Claude"))),
  claude: () => existsSync(resolve(homedir(), ".claude")) || onPath("claude"),
  cursor: () =>
    existsSync("/Applications/Cursor.app") ||
    existsSync(resolve(homedir(), ".cursor")) ||
    onPath("cursor"),
  vscode: () =>
    existsSync("/Applications/Visual Studio Code.app") ||
    existsSync(resolve(homedir(), ".vscode")) ||
    onPath("code"),
  codex: () => existsSync(resolve(homedir(), ".codex")) || onPath("codex"),
};

/** Client ids that look installed on this machine, in registry order. */
export function detectClients(): string[] {
  return CLIENTS.map((c) => c.id).filter((id) => CLIENT_DETECT[id]?.() ?? false);
}

/**
 * Interactively offer an LLM API key, explaining the trade-off. Only prompts on
 * a real TTY; otherwise returns undefined so non-interactive runs stay keyless.
 */
/**
 * Interactive memory-engine selection: offline (heuristic + keyword) or an LLM
 * provider via LiteLLM. Returns a ProviderConfig, or null for offline. Only runs
 * on a TTY; the API key is read inline but never echoed back in any summary.
 */
async function promptMemoryEngine(out: Output): Promise<ProviderConfig | null> {
  if (!process.stdin.isTTY) return null;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> => new Promise((res) => rl.question(q, res));
  try {
    out.log("");
    out.log(bold("How should Statewave build and search memory?"));
    out.log(`  ${cyan("1")}. ${bold("Configure an LLM provider")} ${green("(recommended)")} — cleaner fact extraction + semantic retrieval (LiteLLM).`);
    out.log(`  ${cyan("2")}. Local / offline — built-in heuristic compiler + keyword retrieval. No key, no cost.`);
    const mode = (await ask(`  ${dim("Enter = recommended (LLM provider), 2 = local/offline")}: `)).trim();
    // Enter or "1" → provider flow (falls back to offline if no key is entered).
    if (mode === "2") return null;

    out.log("");
    out.log("Statewave connects through LiteLLM — not just OpenAI. Choose a provider:");
    PROVIDERS.forEach((p, i) => out.log(`  ${cyan(String(i + 1))}. ${p.label}`));
    const provider = PROVIDERS[Number.parseInt((await ask(`  ${dim("number")}: `)).trim(), 10) - 1];
    if (!provider) {
      out.warn("no provider selected — using local/offline.");
      return null;
    }

    const modelHint = provider.defaultModel || "enter a LiteLLM model id";
    const model = (await ask(`  Model ${dim(`[Enter = ${modelHint}]`)}: `)).trim() || provider.defaultModel;

    let apiKey: string | undefined;
    if (provider.needsApiKey) {
      apiKey =
        (await ask(`  API key ${dim("(never written to config or printed in summaries)")}: `)).trim() ||
        undefined;
      if (!apiKey) {
        out.warn("no API key entered — using local/offline.");
        return null;
      }
    }

    let apiBase: string | undefined;
    if (provider.needsApiBase) {
      const baseHint = provider.defaultApiBase ? `[Enter = ${provider.defaultApiBase}]` : "(required)";
      apiBase = (await ask(`  API base URL ${dim(baseHint)}: `)).trim() || provider.defaultApiBase;
    }

    let embeddingModel: string | undefined;
    if (!provider.defaultEmbeddingModel) {
      out.log(dim(`  ${provider.label} has no embedding model — retrieval uses keywords unless you add one.`));
      embeddingModel = (await ask(`  Embedding model ${dim("[Enter = keyword retrieval]")}: `)).trim() || undefined;
    }

    return { provider: provider.id, model, apiKey, apiBase, embeddingModel };
  } finally {
    rl.close();
  }
}

/**
 * Parse a client-selection answer into the chosen clients. Pure, so it's unit
 * tested directly. Empty (just Enter) selects the detected set (or all, if none
 * were detected); `a`/`all` selects everything; `n`/`none` selects nothing;
 * otherwise it's 1-based indices into the full registry (`1,3` / `1 3`).
 */
export function parseClientSelection(answer: string, detected: ClientDef[]): ClientDef[] {
  const t = answer.trim().toLowerCase();
  if (t === "") return detected.length ? detected : CLIENTS.slice();
  if (t === "a" || t === "all") return CLIENTS.slice();
  if (t === "n" || t === "none") return [];
  const nums = t
    .split(/[\s,]+/)
    .map((x) => Number.parseInt(x, 10))
    .filter((n) => Number.isInteger(n) && n >= 1 && n <= CLIENTS.length);
  return [...new Set(nums)].map((n) => CLIENTS[n - 1]!);
}

/** Interactively show the registry (marking what's detected) and let the user pick. */
async function promptClientSelection(out: Output, detectedIds: Set<string>): Promise<ClientDef[]> {
  const detected = CLIENTS.filter((c) => detectedIds.has(c.id));
  out.log("");
  out.log(bold("Which MCP clients should I set up?"));
  CLIENTS.forEach((c, i) => {
    const mark = detectedIds.has(c.id) ? green("✓ detected") : gray("not detected");
    out.log(`  ${cyan(String(i + 1))}. ${c.label.padEnd(24)} ${mark}`);
  });
  const hint = detected.length
    ? "Enter = detected, 'a' = all, e.g. 1,3 = pick, 'n' = none"
    : "'a' = all, e.g. 1,3 = pick, 'n' = none";
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const answer = await new Promise<string>((res) => rl.question(`  ${dim(hint)}: `, res));
    const chosen = parseClientSelection(answer, detected);
    const t = answer.trim().toLowerCase();
    if (chosen.length === 0 && t !== "" && t !== "n" && t !== "none") {
      out.warn("didn't recognize that selection — using the detected clients");
      return detected.length ? detected : CLIENTS.slice();
    }
    return chosen;
  } finally {
    rl.close();
  }
}

// The Statewave IDE Companion — the *capture* half: it auto-ingests your file
// and git activity into Statewave as you work. Complements the MCP config,
// which only lets the assistant *read* memory. Cross-platform resolution +
// verified install live in ./extensions.ts (EXTENSION_ID, installAndVerify,
// isEditorClient), unit-tested across the full 8-case matrix.

/**
 * Verified episode count for a subject, read from `/v1/timeline` — which reads
 * the episodes table directly. We deliberately do NOT use `/v1/subjects`: it's a
 * lagging aggregate that can report 0 right after a write (confirmed against the
 * live server), so trusting it would produce false "seeding failed" results.
 * Returns null on any error. Memory count is intentionally omitted — compilation
 * is asynchronous, so it isn't reliably non-zero immediately after seeding.
 */
export async function subjectCounts(
  baseUrl: string,
  subject: string,
  fetchImpl: typeof fetch = fetch,
): Promise<{ episodes: number } | null> {
  try {
    const url = `${baseUrl.replace(/\/+$/, "")}/v1/timeline?subject_id=${encodeURIComponent(subject)}&limit=1000`;
    const res = await fetchImpl(url);
    if (!res.ok) return null;
    const data = (await res.json()) as { episodes?: unknown[] };
    return Array.isArray(data.episodes) ? { episodes: data.episodes.length } : null;
  } catch {
    return null;
  }
}

/** Parse a 1-based multi-select over `count` discovered repos. Pure (tested). */
export function parseRepoSelection(answer: string, count: number): number[] {
  const t = answer.trim().toLowerCase();
  if (t === "" || t === "a" || t === "all") return Array.from({ length: count }, (_, i) => i);
  if (t === "n" || t === "none") return [];
  const nums = t
    .split(/[\s,]+/)
    .map((x) => Number.parseInt(x, 10))
    .filter((n) => Number.isInteger(n) && n >= 1 && n <= count);
  return [...new Set(nums)].map((n) => n - 1);
}

function showRepoList(out: Output, repos: RepoIdentity[]): void {
  repos.forEach((r, i) => {
    out.log(`  ${cyan(String(i + 1))}. ${bold(r.subject)}${gray(`  ${r.root}`)}${r.fromRemote ? "" : dim("  (no remote)")}`);
  });
}

async function ask(rl: ReturnType<typeof createInterface>, q: string): Promise<string> {
  return (await new Promise<string>((res) => rl.question(q, res))).trim();
}

/** Discover under a root, then let the user multi-select. */
async function discoverAndPick(out: Output, root: string): Promise<RepoIdentity[]> {
  const { repos, truncated } = discoverRepos(resolve(root));
  if (repos.length === 0) {
    out.log(dim(`  No git repositories found under ${root}.`));
    return [];
  }
  out.log("");
  out.log(`Found ${repos.length}${truncated ? "+ (truncated)" : ""} repositories under ${root}:`);
  showRepoList(out, repos);
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const sel = parseRepoSelection(
      await ask(rl, `  ${dim("Enter/a = all, e.g. 1,3 = pick, n = none")}: `),
      repos.length,
    );
    return sel.map((i) => repos[i]!);
  } finally {
    rl.close();
  }
}

/** Interactive repository selection: current repo, discover, path, or skip. */
async function promptRepoSelection(out: Output, identity: RepoIdentity | undefined): Promise<RepoIdentity[]> {
  out.log("");
  out.log(bold("Which repositories should Statewave seed?"));
  let n = 0;
  const opts: Array<"current" | "discover" | "path" | "skip"> = [];
  if (identity) {
    out.log(`  ${cyan(String(++n))}. Current repository  ${gray(identity.root)}  → ${bold(identity.subject)}`);
    opts.push("current");
  }
  out.log(`  ${cyan(String(++n))}. Discover repositories under a folder`);
  opts.push("discover");
  out.log(`  ${cyan(String(++n))}. Enter a repository path`);
  opts.push("path");
  out.log(`  ${cyan(String(++n))}. Skip seeding`);
  opts.push("skip");

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const def = identity ? "current" : "discover";
    const raw = await ask(rl, `  ${dim(`Enter = ${def === "current" ? "current repo" : "discover"}`)}: `);
    const choice = raw === "" ? def : opts[Number.parseInt(raw, 10) - 1];
    rl.close();
    switch (choice) {
      case "current":
        return identity ? [identity] : [];
      case "discover": {
        const root = await (async () => {
          const r2 = createInterface({ input: process.stdin, output: process.stdout });
          try {
            return (await ask(r2, `  Folder to search ${dim(`[Enter = ${process.cwd()}]`)}: `)) || process.cwd();
          } finally {
            r2.close();
          }
        })();
        return discoverAndPick(out, root);
      }
      case "path": {
        const r3 = createInterface({ input: process.stdin, output: process.stdout });
        try {
          const p = await ask(r3, "  Repository path: ");
          const id = p ? resolveRepoIdentity(resolve(p)) : undefined;
          if (!id) out.warn(`${p || "(empty)"} is not a git repository.`);
          return id ? [id] : [];
        } finally {
          r3.close();
        }
      }
      default:
        return [];
    }
  } finally {
    // rl already closed in the happy path; closing twice is a no-op.
    rl.close();
  }
}

/** Resolve the repositories to seed from flags or interaction. */
async function selectRepos(
  out: Output,
  args: ParsedArgs,
  identity: RepoIdentity | undefined,
  explicitSubject: string | undefined,
): Promise<RepoIdentity[]> {
  if (explicitSubject) {
    return [{ root: identity?.root ?? process.cwd(), subject: explicitSubject, fromRemote: identity?.fromRemote ?? false }];
  }
  const reposFlag = flagAsString(args, "repos");
  if (reposFlag) {
    return reposFlag
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
      .map((p) => resolveRepoIdentity(resolve(p)))
      .filter((r): r is RepoIdentity => Boolean(r));
  }
  const discoverRoot = flagAsString(args, "discover");
  if (discoverRoot) {
    if (process.stdin.isTTY && !out.isJson() && !flagAsBool(args, "yes")) return discoverAndPick(out, discoverRoot);
    return discoverRepos(resolve(discoverRoot)).repos;
  }
  if (process.stdin.isTTY && !out.isJson() && !flagAsBool(args, "yes")) {
    return promptRepoSelection(out, identity);
  }
  return identity ? [identity] : [];
}

/**
 * Client-specific "test it here" steps with the correct reload behavior:
 * CLI clients need a new terminal; editors need a window reload; the chat app
 * needs a full restart and picks the subject in-app.
 */
function clientTestSteps(client: ClientDef, root: string, subject: string): string[] {
  const ask = `Ask: ${cyan(`"What changed recently in this repository?"`)}`;
  switch (client.id) {
    case "claude":
      return [`Open a terminal in ${root} and run \`claude\`.`, ask];
    case "codex":
      return [`Open a terminal in ${root} and run \`codex\`.`, ask];
    case "cursor":
      return [`Open ${root} in Cursor (reload the window if it was already open), then open Agent chat.`, ask];
    case "vscode":
      return [`Open ${root} in VS Code (reload the window), then open Copilot Chat in Agent mode.`, ask];
    case "claude-desktop":
      return [
        "Quit and reopen Claude Desktop, then start a new chat.",
        `Ask it to list available repository subjects and pick ${bold(subject)}.`,
      ];
    default:
      return [`Open ${client.label} and ask it about subject ${subject}.`];
  }
}

export async function runQuickstart(args: ParsedArgs): Promise<number> {
  const out = new Output({ json: flagAsBool(args, "json") });
  const cwd = process.cwd();
  const apiPort = flagAsInt(args, "api-port") ?? 8100;
  const adminPort = flagAsInt(args, "admin-port") ?? 8080;
  const includeAdmin = !flagAsBool(args, "no-admin");
  const doSeed = !flagAsBool(args, "no-seed");
  const baseUrl = flagAsString(args, "statewave-url") ?? `http://localhost:${apiPort}`;
  // Subject comes from real git identity (remote → repo:owner/name, else the
  // work-tree basename), NOT the cwd name. Undefined when this isn't a repo and
  // no explicit --subject was given — we then skip seeding rather than invent a
  // bogus subject like `repo:<home-dir>`.
  const identity = resolveRepoIdentity(cwd);
  const subject = flagAsString(args, "subject") ?? identity?.subject;
  // Optional-stage warnings; the final summary and exit reflect them honestly.
  const warnings: string[] = [];

  if (flagAsBool(args, "down")) {
    if (!existsSync(COMPOSE_PATH)) {
      out.log("No quickstart stack found — nothing to stop.");
      return 0;
    }
    const downArgs = ["compose", "-p", PROJECT_NAME, "-f", COMPOSE_PATH, "down"];
    if (flagAsBool(args, "purge")) downArgs.push("--volumes");
    try {
      execFileSync("docker", downArgs, { stdio: "inherit" });
      out.log("Quickstart stack stopped.");
      return 0;
    } catch (err) {
      out.error(`docker compose down failed: ${(err as Error).message}`);
      return 1;
    }
  }

  // Environment preflight (informational): Node already runs this code; Git is
  // needed for repo identity + seeding. Docker is checked lazily, only if we
  // actually need to start a server.
  if (!nodeMeetsMinimum(process.version)) {
    out.warn(`Node ${process.version} is below the supported minimum (>= ${MIN_NODE_MAJOR}); some steps may misbehave.`);
  }
  if (!gitAvailable()) {
    out.warn("git not found on PATH — repository detection and seeding will be skipped.");
  }

  // Which clients to configure: explicit --client a,b,c | --all | interactive pick | auto-detect.
  let clients: ClientDef[];
  {
    const explicit = flagAsString(args, "client");
    if (explicit) {
      const resolved: ClientDef[] = [];
      for (const id of explicit.split(",").map((s) => s.trim()).filter(Boolean)) {
        const c = findClient(id);
        if (!c) {
          out.error(`unknown client: ${id}`, `supported: ${CLIENTS.map((x) => x.id).join(", ")}`);
          return 2;
        }
        resolved.push(c);
      }
      clients = resolved;
    } else if (flagAsBool(args, "all")) {
      clients = CLIENTS.slice();
    } else {
      const detectedIds = new Set(detectClients());
      const detected = CLIENTS.filter((c) => detectedIds.has(c.id));
      const interactive = !!process.stdin.isTTY && !out.isJson();
      const assumeYes = flagAsBool(args, "yes") || flagAsBool(args, "y");
      if (interactive && !assumeYes) {
        clients = await promptClientSelection(out, detectedIds);
      } else if (detected.length) {
        clients = detected;
        out.log(dim(`Configuring detected clients: ${detected.map((c) => c.id).join(", ")} (--client to narrow).`));
      } else {
        clients = [findClient("claude-desktop")!];
        out.log(dim("No MCP clients detected — defaulting to Claude Desktop (use --client/--all)."));
      }
    }
  }
  if (clients.length === 0) {
    out.log(dim("No clients selected — starting/seeding the server but configuring nothing."));
  }

  // Memory engine: offline heuristic by default, or an LLM provider via LiteLLM.
  // Provider config only matters when WE start the server (a reused server is
  // already configured). Resolve flag/env config up front to warn on reuse.
  const forceOffline = flagAsBool(args, "no-llm");
  const flagKey = forceOffline
    ? undefined
    : flagAsString(args, "llm-api-key") ??
      process.env.STATEWAVE_LITELLM_API_KEY ??
      process.env.OPENAI_API_KEY;
  const flagProvider = forceOffline ? undefined : flagAsString(args, "provider");
  let providerConfig: ProviderConfig | undefined =
    !forceOffline && (flagProvider || flagKey)
      ? {
          provider: flagProvider ?? "openai",
          model: flagAsString(args, "llm-model"),
          apiKey: flagKey,
          apiBase: flagAsString(args, "api-base"),
          embeddingModel: flagAsString(args, "embedding-model"),
        }
      : undefined;

  // 1. Server — reuse an existing healthy one, otherwise bring up the stack.
  let startedStack = false;
  if (await checkHealth(baseUrl)) {
    out.log(`${green("✓")} Statewave server already running at ${baseUrl} — reusing it.`);
    if (providerConfig) {
      out.warn(
        "an LLM provider was configured, but quickstart is reusing an already-running server — " +
          "it has no effect here; configure the provider on that server instead",
      );
    }
  } else {
    if (!(await ensureDockerReady(out))) return 1;
    // Choose the memory engine before starting (interactive when none was given).
    if (!providerConfig && !forceOffline && !flagAsBool(args, "no-llm-prompt") && !out.isJson()) {
      providerConfig = (await promptMemoryEngine(out)) ?? undefined;
    }
    const llmEnvVars = providerConfig ? buildProviderEnv(providerConfig) : {};
    const memoryLabel = providerConfig
      ? `LLM compiler via ${providerConfig.provider}${
          llmEnvVars.STATEWAVE_EMBEDDING_PROVIDER === "litellm"
            ? " + semantic embeddings"
            : " + keyword retrieval (provider has no embeddings)"
        }`
      : "offline heuristic compiler + keyword retrieval (no key, no cost)";
    out.log("");
    out.log(bold(`Starting Statewave (api${includeAdmin ? " + admin" : ""} + db) via docker compose…`));
    out.log(`  memory: ${memoryLabel}`);
    await mkdir(STATE_DIR, { recursive: true });
    await writeFile(COMPOSE_PATH, renderComposeFile({ apiPort, adminPort, includeAdmin }), "utf8");
    try {
      execFileSync("docker", ["compose", "-p", PROJECT_NAME, "-f", COMPOSE_PATH, "up", "-d"], {
        stdio: "inherit",
        // Pass the provider env to compose; the compose file interpolates these
        // so the API key never lands on disk.
        env: { ...process.env, ...llmEnvVars },
      });
    } catch (err) {
      out.error(`docker compose up failed: ${(err as Error).message}`);
      return 1;
    }
    const healthy = await withSpinner(
      "Waiting for the API to become healthy…",
      () => waitForHealth(baseUrl, { timeoutMs: 180_000, intervalMs: 2_000 }),
      { active: !out.isJson() },
    );
    if (!healthy) {
      out.error(
        `server did not become healthy at ${baseUrl} within 3 minutes`,
        `inspect logs: docker compose -p ${PROJECT_NAME} -f ${COMPOSE_PATH} logs api`,
      );
      return 1;
    }
    startedStack = true;
    out.log(`${green("✓")} Server healthy at ${baseUrl}.`);
  }

  // Select the repositories to set up (config + seed) BEFORE configuring clients,
  // so project-scoped clients are configured INSIDE each selected repository.
  const reposToSeed = doSeed ? await selectRepos(out, args, identity, flagAsString(args, "subject")) : [];

  // 2. Configure clients. Project-scoped clients (Claude Code, Cursor, VS Code)
  //    — and any client with a repo instruction file (Codex) — are written into
  //    each selected repository so opening any of them targets that repo's
  //    subject. Pure user-scoped chat apps (Claude Desktop) are configured once.
  const serverBin = resolveLocalServerBin();
  const spec = buildServerSpec({ statewaveUrl: baseUrl, serverBin });
  let pasteBlock: string | undefined;
  out.log("");
  const configTargets: Array<{ root: string; subject: string }> = reposToSeed.length
    ? reposToSeed.map((r) => ({ root: r.root, subject: r.subject }))
    : [{ root: identity?.root ?? cwd, subject: subject ?? "repo:workspace" }];
  const noSubjectAnywhere = reposToSeed.length === 0 && !subject;
  for (const client of clients) {
    try {
      const perRepo = client.scope === "project" || Boolean(client.instructionFile);
      const targets = perRepo ? configTargets : configTargets.slice(0, 1);
      let lastPaste: string | undefined;
      for (const t of targets) {
        const r = await writeInit(client, spec, t.subject, t.root, {
          skipInstructions: flagAsBool(args, "no-instructions") || noSubjectAnywhere,
        });
        if (r.pasteBlock) lastPaste = r.pasteBlock;
      }
      if (lastPaste) pasteBlock = lastPaste;
      out.log(
        `${green("✓")} Configured ${bold(client.label)}${targets.length > 1 ? gray(` (${targets.length} repos)`) : ""}`,
      );
    } catch (err) {
      out.error(`failed to configure ${client.label}: ${(err as Error).message}`);
      return 1;
    }
  }

  // 2b. Install the IDE Companion (capture side) for any chosen editor. Picking
  //     VS Code / Cursor is the consent — no second prompt. Opt out with
  //     --no-install-extension. Failures are soft (don't fail the whole run).
  if (!flagAsBool(args, "no-install-extension")) {
    const editors = clients.filter((c) => isEditorClient(c.id));
    if (editors.length) out.log("");
    const vsix = flagAsString(args, "extension-vsix");
    const target = vsix ?? EXTENSION_ID;
    const handled = new Set<string>(); // resolved binaries — forks sharing a CLI are handled once
    for (const e of editors) {
      const r = installAndVerify(e.id, target, { vsixGiven: Boolean(vsix) });
      const via =
        r.via && !e.label.includes(r.via) && !r.via.includes(e.label) ? `${e.label} (${r.via})` : e.label;
      if (r.binary && handled.has(r.binary)) {
        out.log(dim(`  ${e.label}: same editor as a prior selection (${r.via}) — already handled.`));
        continue;
      }
      if (r.binary) handled.add(r.binary);
      switch (r.status) {
        case "no-cli":
          warnings.push(`${e.label}: editor CLI not found — IDE Companion not installed`);
          out.log(`  ${yellow("!")} ${e.label}: CLI not found — install "${EXTENSION_ID}" from its Extensions panel.`);
          break;
        case "already":
          out.log(`${green("✓")} IDE Companion already installed in ${bold(via)}`);
          break;
        case "installed":
        case "updated":
          out.log(`${green("✓")} IDE Companion ${r.status} and verified in ${bold(via)}`);
          break;
        case "failed":
          warnings.push(`IDE Companion install failed in ${via}`);
          out.log(`  ${red("✗")} IDE Companion install failed in ${bold(via)}: ${r.message}`);
          out.log(dim(`    Install manually: open ${e.label} → Extensions → search "${EXTENSION_ID}".`));
          break;
        case "unverified":
          warnings.push(`IDE Companion install in ${via} could not be verified`);
          out.log(`  ${yellow("!")} IDE Companion install reported success in ${bold(via)} but couldn't be verified — open its Extensions panel to confirm.`);
          break;
      }
    }
  }

  // 3. Repository selection + seeding (zero, one, or many). Counts are verified
  //    against the server, never trusted from the seed command's own output.
  interface SeedResult { subject: string; root: string; ok: boolean; episodes?: number }
  const seedResults: SeedResult[] = [];
  if (doSeed && reposToSeed.length === 0) {
    out.log("");
    out.log(dim("No repository selected — seeding skipped. Seed later: statewave-connectors mcp seed --write"));
  }
  for (const repo of reposToSeed) {
    out.log("");
    out.log(bold(`Seeding ${repo.subject}`) + dim(`  (${repo.root})`));
    const seedCode = await runMcpSeed({
      positional: ["mcp", "seed"],
      flags: { subject: repo.subject, write: true, "statewave-url": baseUrl, "repo-path": repo.root },
    });
    const counts = await subjectCounts(baseUrl, repo.subject);
    const ok = seedCode === 0 && !!counts && counts.episodes > 0;
    seedResults.push({ subject: repo.subject, root: repo.root, ok, episodes: counts?.episodes });
    if (!ok) warnings.push(`seeding ${repo.subject} did not complete`);
  }

  // 4. Honest summary — status reflects whether optional stages had warnings.
  out.log("");
  out.log(
    warnings.length === 0
      ? bold("Statewave quickstart complete.")
      : bold(`Statewave quickstart completed with ${warnings.length} warning${warnings.length === 1 ? "" : "s"}.`),
  );
  out.log(`  ${green("✓")} Server: ${baseUrl}${startedStack && includeAdmin ? `  ·  admin ${cyan(`http://localhost:${adminPort}`)}` : ""}`);
  if (clients.length) {
    out.log(`  ${green("✓")} Configured: ${clients.map((c) => c.label).join(", ")}`);
  }
  if (doSeed && reposToSeed.length === 0) out.log(`  ${dim("–")} Seeding skipped (no repository selected)`);
  for (const r of seedResults) {
    out.log(
      r.ok
        ? `  ${green("✓")} ${r.subject} — ${r.episodes} episodes (verified)`
        : `  ${yellow("!")} ${r.subject} — seeding failed`,
    );
  }
  const seededOk = seedResults.filter((r) => r.ok);
  for (const w of warnings) out.log(`  ${yellow("!")} ${w}`);

  // What's left for the human — exactly where to test, per configured client.
  const testRepo = seededOk[0] ?? configTargets[0];
  if (clients.length && testRepo) {
    out.log("");
    out.log(bold("Test Statewave"));
    for (const c of clients) {
      out.log(`  ${bold(c.label)}`);
      for (const line of clientTestSteps(c, testRepo.root, testRepo.subject)) out.log(`    • ${line}`);
    }
  }

  // Chat apps (no repo instruction file) can't auto-bind to a subject. Save the
  // optional guidance to a file instead of dumping a block in the terminal — and
  // statewave_list_subjects lets the assistant discover subjects with no manual step.
  if (pasteBlock) {
    const instrPath = resolve(STATE_DIR, "chat-instructions.md");
    try {
      await mkdir(STATE_DIR, { recursive: true });
      await writeFile(instrPath, pasteBlock.trimEnd() + "\n", "utf8");
      out.log("");
      out.log(dim(`  Optional chat-app instructions saved to ${instrPath}`));
      out.log(dim("  (or just ask the chat app to list repository subjects — no manual paste needed)."));
    } catch {
      // non-fatal
    }
  }
  if (startedStack) {
    out.log("");
    out.log(dim("Stop the stack later with: statewave-connectors quickstart --down"));
  }
  return 0;
}
