import { execFileSync } from "node:child_process";
import { existsSync, realpathSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { createInterface } from "node:readline";
import type { ParsedArgs } from "../args.js";
import { flagAsBool, flagAsInt, flagAsString } from "../args.js";
import { bold, cyan, dim, gray, green, red, yellow } from "../colors.js";
import { Output } from "../output.js";
import { withSpinner } from "../spinner.js";
import { buildServerSpec, type ClientDef, CLIENTS, findClient } from "./mcp-clients.js";
import { writeInit } from "./mcp-init.js";
import { runMcpSeed } from "./mcp-seed.js";
import { buildProviderEnv, type ProviderConfig, PROVIDERS } from "./providers.js";
import { resolveRepoIdentity } from "./repo.js";

const STATE_DIR = resolve(homedir(), ".statewave/quickstart");
const COMPOSE_PATH = resolve(STATE_DIR, "docker-compose.yml");
const PROJECT_NAME = "statewave-quickstart";

export interface ComposeOptions {
  apiPort: number;
  adminPort: number;
  includeAdmin: boolean;
  version?: string;
  adminVersion?: string;
}

/**
 * A self-contained compose file pinned to the published images — no local
 * checkout required. It mirrors the project's own compose but drops the
 * `build:` and the `../statewave-docs` volume (which assume a sibling repo) so
 * it runs anywhere. Debug mode means zero API keys and the admin needs no
 * password — a fresh `up -d` just works.
 */
export function renderComposeFile(opts: ComposeOptions): string {
  const tag = opts.version ?? "latest";
  const adminTag = opts.adminVersion ?? "latest";
  const admin = opts.includeAdmin
    ? `  admin:
    image: statewavedev/statewave-admin:${adminTag}
    ports:
      - "${opts.adminPort}:8080"
    environment:
      STATEWAVE_API_URL: http://api:8100
      STATEWAVE_API_KEY: dev-local-placeholder
      NODE_ENV: production
      ADMIN_AUTH_DISABLED: "true"
    depends_on:
      api:
        condition: service_started
`
    : "";
  return `# Generated by \`statewave-connectors quickstart\`. Safe to delete.
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: statewave
      POSTGRES_PASSWORD: statewave
      POSTGRES_DB: statewave
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statewave"]
      interval: 2s
      timeout: 5s
      retries: 15
  api:
    image: statewavedev/statewave:${tag}
    ports:
      - "${opts.apiPort}:8100"
    environment:
      STATEWAVE_DATABASE_URL: postgresql+asyncpg://statewave:statewave@db:5432/statewave
      STATEWAVE_DEBUG: "true"
      STATEWAVE_BOOTSTRAP_DOCS_PACK: "false"
      # LLM compiler + embeddings are off unless a key is supplied. These read
      # from the environment passed to \`docker compose up\` (so the secret is
      # never written to this file); they fall back to the keyless defaults.
      STATEWAVE_COMPILER_TYPE: \${STATEWAVE_COMPILER_TYPE:-heuristic}
      STATEWAVE_EMBEDDING_PROVIDER: \${STATEWAVE_EMBEDDING_PROVIDER:-stub}
      STATEWAVE_LITELLM_API_KEY: \${STATEWAVE_LITELLM_API_KEY:-}
      STATEWAVE_LITELLM_MODEL: \${STATEWAVE_LITELLM_MODEL:-gpt-4o-mini}
      STATEWAVE_LITELLM_EMBEDDING_MODEL: \${STATEWAVE_LITELLM_EMBEDDING_MODEL:-text-embedding-3-small}
    depends_on:
      db:
        condition: service_healthy
${admin}volumes:
  pgdata:
`;
}

/**
 * Server env that turns on the LLM compiler + semantic embeddings when a key is
 * supplied. Empty when there's no key — the server then uses the keyless
 * heuristic compiler + stub embeddings. The key is passed to `docker compose`
 * via the environment, never written to the compose file.
 */
export function llmEnv(apiKey?: string, model?: string): Record<string, string> {
  if (!apiKey) return {};
  const env: Record<string, string> = {
    STATEWAVE_COMPILER_TYPE: "llm",
    STATEWAVE_EMBEDDING_PROVIDER: "litellm",
    STATEWAVE_LITELLM_API_KEY: apiKey,
  };
  if (model) env.STATEWAVE_LITELLM_MODEL = model;
  return env;
}

export async function checkHealth(baseUrl: string, fetchImpl: typeof fetch = fetch): Promise<boolean> {
  try {
    const res = await fetchImpl(`${baseUrl.replace(/\/+$/, "")}/healthz`, { method: "GET" });
    return res.ok;
  } catch {
    return false;
  }
}

export async function waitForHealth(
  baseUrl: string,
  opts: { timeoutMs: number; intervalMs: number; fetchImpl?: typeof fetch; onTick?: () => void },
): Promise<boolean> {
  const deadline = Date.now() + opts.timeoutMs;
  while (Date.now() < deadline) {
    if (await checkHealth(baseUrl, opts.fetchImpl)) return true;
    opts.onTick?.();
    await new Promise((r) => setTimeout(r, opts.intervalMs));
  }
  return checkHealth(baseUrl, opts.fetchImpl);
}

/** Resolve the absolute path to the mcp-server bin this CLI ships with. */
function resolveLocalServerBin(): string | undefined {
  try {
    const req = createRequire(import.meta.url);
    const pkgPath = req.resolve("@statewavedev/mcp-server/package.json");
    const pkg = req("@statewavedev/mcp-server/package.json") as { bin?: string | Record<string, string> };
    const binRel =
      typeof pkg.bin === "string" ? pkg.bin : pkg.bin ? Object.values(pkg.bin)[0] : undefined;
    return binRel ? resolve(dirname(pkgPath), binRel) : undefined;
  } catch {
    return undefined;
  }
}

function dockerAvailable(): boolean {
  try {
    execFileSync("docker", ["compose", "version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

/** First absolute path for `bin` on the PATH, or undefined. Cross-platform. */
function resolveOnPath(bin: string): string | undefined {
  const sep = process.platform === "win32" ? ";" : ":";
  const names = process.platform === "win32" ? [`${bin}.exe`, `${bin}.cmd`, bin] : [bin];
  for (const d of (process.env.PATH ?? "").split(sep)) {
    if (!d) continue;
    for (const n of names) {
      const p = join(d, n);
      if (existsSync(p)) return p;
    }
  }
  return undefined;
}

function onPath(bin: string): boolean {
  return resolveOnPath(bin) !== undefined;
}

/**
 * Best-effort editor identity from a resolved CLI path. VS Code forks (Cursor,
 * VSCodium, Windsurf) often ship their own `code` shim, so the `code` command
 * may not be VS Code — we surface what it actually resolved to.
 */
function editorIdentity(realPath: string): string {
  const p = realPath.toLowerCase();
  if (p.includes("cursor")) return "Cursor";
  if (p.includes("vscodium")) return "VSCodium";
  if (p.includes("windsurf")) return "Windsurf";
  if (p.includes("code")) return "VS Code";
  return realPath;
}

// Best-effort "is this client installed?" — a config dir, an app bundle, or the
// binary on PATH. Used to pick sensible defaults; --client / --all always win.
const CLIENT_DETECT: Record<string, () => boolean> = {
  "claude-desktop": () =>
    existsSync(resolve(homedir(), "Library/Application Support/Claude")) ||
    existsSync(resolve(homedir(), ".config/Claude")) ||
    (!!process.env.APPDATA && existsSync(join(process.env.APPDATA, "Claude"))),
  claude: () => existsSync(resolve(homedir(), ".claude")) || onPath("claude"),
  cursor: () =>
    existsSync("/Applications/Cursor.app") ||
    existsSync(resolve(homedir(), ".cursor")) ||
    onPath("cursor"),
  vscode: () =>
    existsSync("/Applications/Visual Studio Code.app") ||
    existsSync(resolve(homedir(), ".vscode")) ||
    onPath("code"),
  codex: () => existsSync(resolve(homedir(), ".codex")) || onPath("codex"),
};

/** Client ids that look installed on this machine, in registry order. */
export function detectClients(): string[] {
  return CLIENTS.map((c) => c.id).filter((id) => CLIENT_DETECT[id]?.() ?? false);
}

/**
 * Interactively offer an LLM API key, explaining the trade-off. Only prompts on
 * a real TTY; otherwise returns undefined so non-interactive runs stay keyless.
 */
/**
 * Interactive memory-engine selection: offline (heuristic + keyword) or an LLM
 * provider via LiteLLM. Returns a ProviderConfig, or null for offline. Only runs
 * on a TTY; the API key is read inline but never echoed back in any summary.
 */
async function promptMemoryEngine(out: Output): Promise<ProviderConfig | null> {
  if (!process.stdin.isTTY) return null;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> => new Promise((res) => rl.question(q, res));
  try {
    out.log("");
    out.log(bold("How should Statewave build and search memory?"));
    out.log(`  ${cyan("1")}. Local / offline — built-in heuristic compiler + keyword retrieval. No key, no cost.`);
    out.log(`  ${cyan("2")}. Configure an LLM provider (LiteLLM) — cleaner extraction + semantic retrieval.`);
    const mode = (await ask(`  ${dim("Enter = local/offline, 2 = provider")}: `)).trim();
    if (mode !== "2") return null;

    out.log("");
    out.log("Statewave connects through LiteLLM — not just OpenAI. Choose a provider:");
    PROVIDERS.forEach((p, i) => out.log(`  ${cyan(String(i + 1))}. ${p.label}`));
    const provider = PROVIDERS[Number.parseInt((await ask(`  ${dim("number")}: `)).trim(), 10) - 1];
    if (!provider) {
      out.warn("no provider selected — using local/offline.");
      return null;
    }

    const modelHint = provider.defaultModel || "enter a LiteLLM model id";
    const model = (await ask(`  Model ${dim(`[Enter = ${modelHint}]`)}: `)).trim() || provider.defaultModel;

    let apiKey: string | undefined;
    if (provider.needsApiKey) {
      apiKey =
        (await ask(`  API key ${dim("(never written to config or printed in summaries)")}: `)).trim() ||
        undefined;
      if (!apiKey) {
        out.warn("no API key entered — using local/offline.");
        return null;
      }
    }

    let apiBase: string | undefined;
    if (provider.needsApiBase) {
      const baseHint = provider.defaultApiBase ? `[Enter = ${provider.defaultApiBase}]` : "(required)";
      apiBase = (await ask(`  API base URL ${dim(baseHint)}: `)).trim() || provider.defaultApiBase;
    }

    let embeddingModel: string | undefined;
    if (!provider.defaultEmbeddingModel) {
      out.log(dim(`  ${provider.label} has no embedding model — retrieval uses keywords unless you add one.`));
      embeddingModel = (await ask(`  Embedding model ${dim("[Enter = keyword retrieval]")}: `)).trim() || undefined;
    }

    return { provider: provider.id, model, apiKey, apiBase, embeddingModel };
  } finally {
    rl.close();
  }
}

/**
 * Parse a client-selection answer into the chosen clients. Pure, so it's unit
 * tested directly. Empty (just Enter) selects the detected set (or all, if none
 * were detected); `a`/`all` selects everything; `n`/`none` selects nothing;
 * otherwise it's 1-based indices into the full registry (`1,3` / `1 3`).
 */
export function parseClientSelection(answer: string, detected: ClientDef[]): ClientDef[] {
  const t = answer.trim().toLowerCase();
  if (t === "") return detected.length ? detected : CLIENTS.slice();
  if (t === "a" || t === "all") return CLIENTS.slice();
  if (t === "n" || t === "none") return [];
  const nums = t
    .split(/[\s,]+/)
    .map((x) => Number.parseInt(x, 10))
    .filter((n) => Number.isInteger(n) && n >= 1 && n <= CLIENTS.length);
  return [...new Set(nums)].map((n) => CLIENTS[n - 1]!);
}

/** Interactively show the registry (marking what's detected) and let the user pick. */
async function promptClientSelection(out: Output, detectedIds: Set<string>): Promise<ClientDef[]> {
  const detected = CLIENTS.filter((c) => detectedIds.has(c.id));
  out.log("");
  out.log(bold("Which MCP clients should I set up?"));
  CLIENTS.forEach((c, i) => {
    const mark = detectedIds.has(c.id) ? green("✓ detected") : gray("not detected");
    out.log(`  ${cyan(String(i + 1))}. ${c.label.padEnd(24)} ${mark}`);
  });
  const hint = detected.length
    ? "Enter = detected, 'a' = all, e.g. 1,3 = pick, 'n' = none"
    : "'a' = all, e.g. 1,3 = pick, 'n' = none";
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const answer = await new Promise<string>((res) => rl.question(`  ${dim(hint)}: `, res));
    const chosen = parseClientSelection(answer, detected);
    const t = answer.trim().toLowerCase();
    if (chosen.length === 0 && t !== "" && t !== "n" && t !== "none") {
      out.warn("didn't recognize that selection — using the detected clients");
      return detected.length ? detected : CLIENTS.slice();
    }
    return chosen;
  } finally {
    rl.close();
  }
}

// The Statewave IDE Companion — the *capture* half: it auto-ingests your file
// and git activity into Statewave as you work. Complements the MCP config,
// which only lets the assistant *read* memory. Only the VS Code-family editors
// run extensions; each has its own install CLI.
const EXTENSION_ID = "statewavedev.statewave-ide-companion";
const EDITOR_CLI: Record<string, string> = { vscode: "code", cursor: "cursor" };

// Where each editor keeps its OWN bundled CLI. We resolve these first so we
// target the editor the user actually picked — VS Code forks (Cursor, …) ship
// a `code` shim that launches the fork, so PATH lookup alone would install into
// whichever `code` wins, not both. App-bundle paths are unambiguous.
const EDITOR_BINS: Record<string, { command: string; appName: string; binNames: string[] }> = {
  vscode: { command: "code", appName: "Visual Studio Code", binNames: ["code"] },
  cursor: { command: "cursor", appName: "Cursor", binNames: ["cursor", "code"] },
};

/**
 * Resolve an editor client's install CLI to a concrete binary, preferring the
 * editor's own app bundle (macOS) so picking both VS Code and Cursor installs
 * into both — not just whichever `code` resolves to. Falls back to the PATH
 * command on other platforms or when no bundle is found.
 */
function resolveEditorCli(clientId: string): string | undefined {
  const spec = EDITOR_BINS[clientId];
  if (!spec) return undefined;
  if (process.platform === "darwin") {
    const roots = [`/Applications/${spec.appName}.app`, resolve(homedir(), `Applications/${spec.appName}.app`)];
    for (const root of roots) {
      for (const bin of spec.binNames) {
        const p = `${root}/Contents/Resources/app/bin/${bin}`;
        if (existsSync(p)) return p;
      }
    }
  }
  return resolveOnPath(spec.command);
}

function lastLine(text: string): string {
  const lines = text.split("\n").map((l) => l.trim()).filter(Boolean);
  return lines[lines.length - 1] ?? "";
}

/** Extension ids already installed in the editor behind `cli` (lowercased). */
function listInstalledExtensions(cli: string): Set<string> {
  try {
    const stdout = execFileSync(cli, ["--list-extensions"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return new Set(stdout.split("\n").map((s) => s.trim().toLowerCase()).filter(Boolean));
  } catch {
    return new Set();
  }
}

function installExtension(cli: string, target: string): { ok: boolean; message: string } {
  try {
    const stdout = execFileSync(cli, ["--install-extension", target, "--force"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return { ok: true, message: lastLine(stdout) || "installed" };
  } catch (err) {
    const e = err as { stderr?: string; message?: string };
    // Editor CLIs spew a multi-line stack; keep just the final summary line.
    return { ok: false, message: lastLine(e.stderr || e.message || "") || "install failed" };
  }
}

export async function runQuickstart(args: ParsedArgs): Promise<number> {
  const out = new Output({ json: flagAsBool(args, "json") });
  const cwd = process.cwd();
  const apiPort = flagAsInt(args, "api-port") ?? 8100;
  const adminPort = flagAsInt(args, "admin-port") ?? 8080;
  const includeAdmin = !flagAsBool(args, "no-admin");
  const doSeed = !flagAsBool(args, "no-seed");
  const baseUrl = flagAsString(args, "statewave-url") ?? `http://localhost:${apiPort}`;
  // Subject comes from real git identity (remote → repo:owner/name, else the
  // work-tree basename), NOT the cwd name. Undefined when this isn't a repo and
  // no explicit --subject was given — we then skip seeding rather than invent a
  // bogus subject like `repo:<home-dir>`.
  const identity = resolveRepoIdentity(cwd);
  const subject = flagAsString(args, "subject") ?? identity?.subject;
  // Optional-stage warnings; the final summary and exit reflect them honestly.
  const warnings: string[] = [];

  if (flagAsBool(args, "down")) {
    if (!existsSync(COMPOSE_PATH)) {
      out.log("No quickstart stack found — nothing to stop.");
      return 0;
    }
    const downArgs = ["compose", "-p", PROJECT_NAME, "-f", COMPOSE_PATH, "down"];
    if (flagAsBool(args, "purge")) downArgs.push("--volumes");
    try {
      execFileSync("docker", downArgs, { stdio: "inherit" });
      out.log("Quickstart stack stopped.");
      return 0;
    } catch (err) {
      out.error(`docker compose down failed: ${(err as Error).message}`);
      return 1;
    }
  }

  // Which clients to configure: explicit --client a,b,c | --all | interactive pick | auto-detect.
  let clients: ClientDef[];
  {
    const explicit = flagAsString(args, "client");
    if (explicit) {
      const resolved: ClientDef[] = [];
      for (const id of explicit.split(",").map((s) => s.trim()).filter(Boolean)) {
        const c = findClient(id);
        if (!c) {
          out.error(`unknown client: ${id}`, `supported: ${CLIENTS.map((x) => x.id).join(", ")}`);
          return 2;
        }
        resolved.push(c);
      }
      clients = resolved;
    } else if (flagAsBool(args, "all")) {
      clients = CLIENTS.slice();
    } else {
      const detectedIds = new Set(detectClients());
      const detected = CLIENTS.filter((c) => detectedIds.has(c.id));
      const interactive = !!process.stdin.isTTY && !out.isJson();
      const assumeYes = flagAsBool(args, "yes") || flagAsBool(args, "y");
      if (interactive && !assumeYes) {
        clients = await promptClientSelection(out, detectedIds);
      } else if (detected.length) {
        clients = detected;
        out.log(dim(`Configuring detected clients: ${detected.map((c) => c.id).join(", ")} (--client to narrow).`));
      } else {
        clients = [findClient("claude-desktop")!];
        out.log(dim("No MCP clients detected — defaulting to Claude Desktop (use --client/--all)."));
      }
    }
  }
  if (clients.length === 0) {
    out.log(dim("No clients selected — starting/seeding the server but configuring nothing."));
  }

  // Memory engine: offline heuristic by default, or an LLM provider via LiteLLM.
  // Provider config only matters when WE start the server (a reused server is
  // already configured). Resolve flag/env config up front to warn on reuse.
  const forceOffline = flagAsBool(args, "no-llm");
  const flagKey = forceOffline
    ? undefined
    : flagAsString(args, "llm-api-key") ??
      process.env.STATEWAVE_LITELLM_API_KEY ??
      process.env.OPENAI_API_KEY;
  const flagProvider = forceOffline ? undefined : flagAsString(args, "provider");
  let providerConfig: ProviderConfig | undefined =
    !forceOffline && (flagProvider || flagKey)
      ? {
          provider: flagProvider ?? "openai",
          model: flagAsString(args, "llm-model"),
          apiKey: flagKey,
          apiBase: flagAsString(args, "api-base"),
          embeddingModel: flagAsString(args, "embedding-model"),
        }
      : undefined;

  // 1. Server — reuse an existing healthy one, otherwise bring up the stack.
  let startedStack = false;
  if (await checkHealth(baseUrl)) {
    out.log(`${green("✓")} Statewave server already running at ${baseUrl} — reusing it.`);
    if (providerConfig) {
      out.warn(
        "an LLM provider was configured, but quickstart is reusing an already-running server — " +
          "it has no effect here; configure the provider on that server instead",
      );
    }
  } else {
    if (!dockerAvailable()) {
      out.error(
        "Docker is required to start a Statewave server",
        "install Docker Desktop, or point --statewave-url at an already-running server",
      );
      return 1;
    }
    // Choose the memory engine before starting (interactive when none was given).
    if (!providerConfig && !forceOffline && !flagAsBool(args, "no-llm-prompt") && !out.isJson()) {
      providerConfig = (await promptMemoryEngine(out)) ?? undefined;
    }
    const llmEnvVars = providerConfig ? buildProviderEnv(providerConfig) : {};
    const memoryLabel = providerConfig
      ? `LLM compiler via ${providerConfig.provider}${
          llmEnvVars.STATEWAVE_EMBEDDING_PROVIDER === "litellm"
            ? " + semantic embeddings"
            : " + keyword retrieval (provider has no embeddings)"
        }`
      : "offline heuristic compiler + keyword retrieval (no key, no cost)";
    out.log("");
    out.log(bold(`Starting Statewave (api${includeAdmin ? " + admin" : ""} + db) via docker compose…`));
    out.log(`  memory: ${memoryLabel}`);
    await mkdir(STATE_DIR, { recursive: true });
    await writeFile(COMPOSE_PATH, renderComposeFile({ apiPort, adminPort, includeAdmin }), "utf8");
    try {
      execFileSync("docker", ["compose", "-p", PROJECT_NAME, "-f", COMPOSE_PATH, "up", "-d"], {
        stdio: "inherit",
        // Pass the provider env to compose; the compose file interpolates these
        // so the API key never lands on disk.
        env: { ...process.env, ...llmEnvVars },
      });
    } catch (err) {
      out.error(`docker compose up failed: ${(err as Error).message}`);
      return 1;
    }
    const healthy = await withSpinner(
      "Waiting for the API to become healthy…",
      () => waitForHealth(baseUrl, { timeoutMs: 180_000, intervalMs: 2_000 }),
      { active: !out.isJson() },
    );
    if (!healthy) {
      out.error(
        `server did not become healthy at ${baseUrl} within 3 minutes`,
        `inspect logs: docker compose -p ${PROJECT_NAME} -f ${COMPOSE_PATH} logs api`,
      );
      return 1;
    }
    startedStack = true;
    out.log(`${green("✓")} Server healthy at ${baseUrl}.`);
  }

  // 2. Configure each client to launch the server this CLI ships with.
  const serverBin = resolveLocalServerBin();
  const spec = buildServerSpec({ statewaveUrl: baseUrl, serverBin });
  let pasteBlock: string | undefined;
  out.log("");
  // Without a real subject (not a git repo, no --subject) we still configure the
  // MCP server, but we must NOT write a repo instruction bound to a guessed
  // subject — so skip the instruction block in that case.
  const skipInstructions = flagAsBool(args, "no-instructions") || !subject;
  for (const client of clients) {
    try {
      const result = await writeInit(client, spec, subject ?? "repo:workspace", cwd, {
        skipInstructions,
      });
      if (result.pasteBlock) pasteBlock = result.pasteBlock;
      out.log(`${green("✓")} Configured ${bold(client.label)}${gray(` (server id: ${spec.name})`)}`);
      for (const a of result.applied) {
        const tag = a.action === "skip" ? "unchanged" : a.action === "create" ? "created" : "updated";
        out.log(`    ${gray(tag.padEnd(9))} ${a.path}`);
      }
    } catch (err) {
      out.error(`failed to configure ${client.label}: ${(err as Error).message}`);
      return 1;
    }
  }

  // 2b. Install the IDE Companion (capture side) for any chosen editor. Picking
  //     VS Code / Cursor is the consent — no second prompt. Opt out with
  //     --no-install-extension. Failures are soft (don't fail the whole run).
  if (!flagAsBool(args, "no-install-extension")) {
    const editors = clients.filter((c) => EDITOR_CLI[c.id]);
    if (editors.length) out.log("");
    const vsix = flagAsString(args, "extension-vsix");
    const target = vsix ?? EXTENSION_ID;
    const installed = new Set<string>(); // resolved binaries, so forks sharing a CLI install once
    for (const e of editors) {
      const binPath = resolveEditorCli(e.id);
      if (!binPath) {
        warnings.push(`${e.label}: editor CLI not found — IDE Companion not installed`);
        out.log(`  ${yellow("!")} ${e.label}: CLI not found in /Applications or PATH — install "${EXTENSION_ID}" from its Extensions panel.`);
        continue;
      }
      let real = binPath;
      try {
        real = realpathSync(binPath);
      } catch {
        // keep binPath
      }
      // Name the editor we actually resolved to (the bundle path is unambiguous);
      // note it when it differs from the client label (a `code`→fork shim).
      const editorName = editorIdentity(real);
      const via = e.label.includes(editorName) || editorName.includes(e.label) ? e.label : `${e.label} (${editorName})`;
      if (installed.has(real)) {
        out.log(dim(`  ${e.label}: same editor binary as a prior selection (${editorName}) — already handled.`));
        continue;
      }
      installed.add(real);

      // Already present? Report it (and skip, unless a local --extension-vsix
      // was given — then reinstall to pick up the local build).
      const already = listInstalledExtensions(binPath).has(EXTENSION_ID.toLowerCase());
      if (already && !vsix) {
        out.log(`${green("✓")} IDE Companion already installed in ${bold(via)}`);
        continue;
      }

      const r = installExtension(binPath, target);
      if (!r.ok) {
        warnings.push(`IDE Companion install failed in ${via}`);
        out.log(`  ${red("✗")} IDE Companion install failed in ${bold(via)}: ${r.message}`);
        out.log(dim(`    Install manually: open ${e.label} → Extensions → search "${EXTENSION_ID}".`));
        continue;
      }
      // Verify by re-listing — a 0 exit from `--install-extension` does not by
      // itself prove the extension is present (registry hiccups, partial installs).
      if (listInstalledExtensions(binPath).has(EXTENSION_ID.toLowerCase())) {
        out.log(`${green("✓")} IDE Companion ${already ? "updated" : "installed"} and verified in ${bold(via)}`);
      } else {
        warnings.push(`IDE Companion install in ${via} could not be verified`);
        out.log(`  ${yellow("!")} IDE Companion install reported success in ${bold(via)} but couldn't be verified — open its Extensions panel to confirm.`);
      }
    }
  }

  // 3. Seed the repository so the first get_context isn't empty.
  let seedStatus: "seeded" | "skipped" | "failed" | "off" = "off";
  if (doSeed) {
    out.log("");
    if (!subject) {
      out.log(dim("Skipping seeding — this directory is not a git repository and no --subject was given."));
      out.log(dim("  Seed later from inside a repo:  statewave-connectors mcp seed --write"));
      seedStatus = "skipped";
    } else {
      if (identity) {
        out.log(dim(`Repository: ${identity.root}${identity.fromRemote ? "" : "  (no remote — local subject)"}`));
      }
      out.log(bold(`Seeding ${subject}…`));
      const seedCode = await runMcpSeed({
        positional: ["mcp", "seed"],
        flags: { subject, write: true, "statewave-url": baseUrl },
      });
      seedStatus = seedCode === 0 ? "seeded" : "failed";
      if (seedStatus === "failed") warnings.push(`seeding ${subject} did not complete (see output above)`);
    }
  }

  // 4. Honest summary — status reflects whether optional stages had warnings.
  out.log("");
  out.log(
    warnings.length === 0
      ? bold("Statewave quickstart complete.")
      : bold(`Statewave quickstart completed with ${warnings.length} warning${warnings.length === 1 ? "" : "s"}.`),
  );
  out.log(`  ${green("✓")} Server: ${baseUrl}${startedStack && includeAdmin ? `  ·  admin ${cyan(`http://localhost:${adminPort}`)}` : ""}`);
  if (clients.length) {
    out.log(`  ${green("✓")} Configured: ${clients.map((c) => c.label).join(", ")}`);
  }
  if (seedStatus === "seeded") out.log(`  ${green("✓")} Seeded ${subject}`);
  else if (seedStatus === "skipped") out.log(`  ${dim("–")} Seeding skipped (no repository)`);
  else if (seedStatus === "failed") out.log(`  ${yellow("!")} Seeding ${subject} failed`);
  for (const w of warnings) out.log(`  ${yellow("!")} ${w}`);

  // What's left for the human.
  out.log("");
  out.log(bold("Next:"));
  if (clients.length) {
    out.log(`  • Restart the configured app(s) so they load the server: ${clients.map((c) => c.label).join(", ")}`);
  }
  if (seedStatus === "seeded") {
    out.log(`  • Ask your assistant: ${cyan(`"What changed recently in this repository?"`)} — it will use Statewave for subject ${subject}.`);
  }
  if (pasteBlock) {
    out.log("");
    out.log(dim("  A configured chat app (no repo instruction file) needs this pasted into its custom instructions:"));
    out.log("");
    out.log(pasteBlock.trimEnd());
  }
  if (startedStack) {
    out.log("");
    out.log(dim("Stop the stack later with: statewave-connectors quickstart --down"));
  }
  return 0;
}
