import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { createInterface } from "node:readline";
import type { ParsedArgs } from "../args.js";
import { flagAsBool, flagAsInt, flagAsString } from "../args.js";
import { bold, cyan, dim, gray, green, red, yellow } from "../colors.js";
import { Output } from "../output.js";
import { withSpinner } from "../spinner.js";
import { EXTENSION_ID, installAndVerify, isEditorClient } from "./extensions.js";
import { listProviderModels, type ModelCatalog, resolveModelAnswer } from "./models.js";
import { buildServerSpec, type ClientDef, CLIENTS, findClient } from "./mcp-clients.js";
import { writeInit } from "./mcp-init.js";
import { runMcpSeed } from "./mcp-seed.js";
import {
  dockerFixHint,
  dockerInstallMethod,
  dockerState,
  type DockerInstallMethod,
  gitAvailable,
  MIN_NODE_MAJOR,
  nodeMeetsMinimum,
} from "./preflight.js";
import { buildProviderEnv, type ProviderConfig, PROVIDERS } from "./providers.js";
import { discoverRepos, resolveRepoIdentity, type RepoIdentity } from "./repo.js";

const STATE_DIR = resolve(homedir(), ".statewave/quickstart");
const COMPOSE_PATH = resolve(STATE_DIR, "docker-compose.yml");
const PROJECT_NAME = "statewave-quickstart";

export interface ComposeOptions {
  apiPort: number;
  adminPort: number;
  includeAdmin: boolean;
  version?: string;
  adminVersion?: string;
}

/**
 * A self-contained compose file pinned to the published images — no local
 * checkout required. It mirrors the project's own compose but drops the
 * `build:` and the `../statewave-docs` volume (which assume a sibling repo) so
 * it runs anywhere. Debug mode means zero API keys and the admin needs no
 * password — a fresh `up -d` just works.
 */
export function renderComposeFile(opts: ComposeOptions): string {
  const tag = opts.version ?? "latest";
  const adminTag = opts.adminVersion ?? "latest";
  const admin = opts.includeAdmin
    ? `  admin:
    image: statewavedev/statewave-admin:${adminTag}
    ports:
      - "${opts.adminPort}:8080"
    environment:
      STATEWAVE_API_URL: http://api:8100
      STATEWAVE_API_KEY: dev-local-placeholder
      NODE_ENV: production
      ADMIN_AUTH_DISABLED: "true"
    depends_on:
      api:
        condition: service_started
`
    : "";
  return `# Generated by \`statewave-connectors quickstart\`. Safe to delete.
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: statewave
      POSTGRES_PASSWORD: statewave
      POSTGRES_DB: statewave
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statewave"]
      interval: 2s
      timeout: 5s
      retries: 15
  api:
    image: statewavedev/statewave:${tag}
    ports:
      - "${opts.apiPort}:8100"
    environment:
      STATEWAVE_DATABASE_URL: postgresql+asyncpg://statewave:statewave@db:5432/statewave
      STATEWAVE_DEBUG: "true"
      STATEWAVE_BOOTSTRAP_DOCS_PACK: "false"
      # LLM compiler + embeddings are off unless a key is supplied. These read
      # from the environment passed to \`docker compose up\` (so the secret is
      # never written to this file); they fall back to the keyless defaults.
      STATEWAVE_COMPILER_TYPE: \${STATEWAVE_COMPILER_TYPE:-heuristic}
      STATEWAVE_EMBEDDING_PROVIDER: \${STATEWAVE_EMBEDDING_PROVIDER:-stub}
      STATEWAVE_LITELLM_API_KEY: \${STATEWAVE_LITELLM_API_KEY:-}
      STATEWAVE_LITELLM_MODEL: \${STATEWAVE_LITELLM_MODEL:-gpt-4o-mini}
      STATEWAVE_LITELLM_EMBEDDING_MODEL: \${STATEWAVE_LITELLM_EMBEDDING_MODEL:-text-embedding-3-small}
    depends_on:
      db:
        condition: service_healthy
${admin}volumes:
  pgdata:
`;
}

/**
 * Server env that turns on the LLM compiler + semantic embeddings when a key is
 * supplied. Empty when there's no key — the server then uses the keyless
 * heuristic compiler + stub embeddings. The key is passed to `docker compose`
 * via the environment, never written to the compose file.
 */
export function llmEnv(apiKey?: string, model?: string): Record<string, string> {
  if (!apiKey) return {};
  const env: Record<string, string> = {
    STATEWAVE_COMPILER_TYPE: "llm",
    STATEWAVE_EMBEDDING_PROVIDER: "litellm",
    STATEWAVE_LITELLM_API_KEY: apiKey,
  };
  if (model) env.STATEWAVE_LITELLM_MODEL = model;
  return env;
}

export async function checkHealth(baseUrl: string, fetchImpl: typeof fetch = fetch): Promise<boolean> {
  try {
    const res = await fetchImpl(`${baseUrl.replace(/\/+$/, "")}/healthz`, { method: "GET" });
    return res.ok;
  } catch {
    return false;
  }
}

export async function waitForHealth(
  baseUrl: string,
  opts: { timeoutMs: number; intervalMs: number; fetchImpl?: typeof fetch; onTick?: () => void },
): Promise<boolean> {
  const deadline = Date.now() + opts.timeoutMs;
  while (Date.now() < deadline) {
    if (await checkHealth(baseUrl, opts.fetchImpl)) return true;
    opts.onTick?.();
    await new Promise((r) => setTimeout(r, opts.intervalMs));
  }
  return checkHealth(baseUrl, opts.fetchImpl);
}

/** Resolve the absolute path to the mcp-server bin this CLI ships with. */
function resolveLocalServerBin(): string | undefined {
  try {
    const req = createRequire(import.meta.url);
    const pkgPath = req.resolve("@statewavedev/mcp-server/package.json");
    const pkg = req("@statewavedev/mcp-server/package.json") as { bin?: string | Record<string, string> };
    const binRel =
      typeof pkg.bin === "string" ? pkg.bin : pkg.bin ? Object.values(pkg.bin)[0] : undefined;
    return binRel ? resolve(dirname(pkgPath), binRel) : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Offer and attempt Docker installation for the `no-cli` case. Returns true when
 * Docker is installed and the caller should loop to re-check the state; false when
 * the user declined, the install failed, or the post-install situation still needs
 * manual steps (Windows — Docker Desktop must be started from the Start menu).
 */
async function offerDockerInstall(out: Output, method: DockerInstallMethod): Promise<boolean> {
  const installCmds: Record<string, string> = {
    brew: "brew install --cask docker",
    winget: "winget install Docker.DockerDesktop --accept-package-agreements",
    "get-docker-sh": "curl -fsSL https://get.docker.com | sh",
  };
  out.log(dim(`  Auto-install available: ${installCmds[method]}`));
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ans = (
    await new Promise<string>((res) =>
      rl.question(`  ${dim("[Y = install Docker now, n = exit]")}: `, res),
    )
  )
    .trim()
    .toLowerCase();
  rl.close();
  if (ans === "n" || ans === "no") return false;

  try {
    out.log(dim("  Installing Docker…"));
    if (method === "brew") {
      execFileSync("brew", ["install", "--cask", "docker"], { stdio: "inherit" });
      out.log(`${green("✓")} Docker Desktop installed via Homebrew.`);
      out.log(dim("  Starting Docker Desktop — waiting up to 30s…"));
      try { execFileSync("open", ["-a", "Docker"], { stdio: "ignore" }); } catch { /* ignore */ }
      for (let i = 0; i < 15; i++) {
        await new Promise((r) => setTimeout(r, 2000));
        if (dockerState() === "ok") return true;
      }
      out.warn("Docker Desktop is installed but the daemon isn't ready yet — use the retry prompt below.");
      return true; // daemon-down loop will handle the rest
    } else if (method === "winget") {
      execFileSync(
        "winget",
        ["install", "Docker.DockerDesktop", "--accept-package-agreements", "--accept-source-agreements"],
        { stdio: "inherit" },
      );
      out.log(`${green("✓")} Docker Desktop installed.`);
      out.log("");
      out.log(bold("  Next — Docker Desktop needs a one-time manual start:"));
      out.log("  1. Open Docker Desktop from the Start menu");
      out.log("  2. Accept the license and complete setup");
      out.log("  3. Wait until Docker Desktop shows 'Running'");
      out.log("  4. Re-run this quickstart");
      return false; // can't auto-continue: daemon not running and PATH not updated
    } else if (method === "get-docker-sh") {
      execFileSync("sh", ["-c", "curl -fsSL https://get.docker.com | sh"], { stdio: "inherit" });
      try { execFileSync("sudo", ["systemctl", "start", "docker"], { stdio: "inherit" }); } catch { /* non-fatal */ }
      try {
        const user = process.env.USER ?? process.env.LOGNAME ?? "";
        if (user) execFileSync("sudo", ["usermod", "-aG", "docker", user], { stdio: "inherit" });
      } catch { /* non-fatal — group change needs re-login anyway */ }
      out.log(`${green("✓")} Docker Engine installed.`);
      return true;
    }
  } catch (err) {
    out.error(`Docker auto-install failed: ${(err as Error).message}`);
    out.log(dim("  Install it manually, then re-run."));
    return false;
  }
  return false;
}

/**
 * Ensure Docker is usable, with OS-specific guidance per failure mode. For a
 * missing install, offers an auto-install via brew / winget / get.docker.com.
 * For a stopped daemon, offers an interactive retry. Returns false when Docker
 * cannot be made ready without a full re-run.
 */
async function ensureDockerReady(out: Output): Promise<boolean> {
  for (;;) {
    const state = dockerState();
    if (state === "ok") return true;
    out.error(
      state === "no-cli"
        ? "Docker is required to start a local Statewave server"
        : state === "no-compose"
          ? "Docker Compose v2 (`docker compose`) is required"
          : state === "daemon-down"
            ? "Docker is installed but the daemon isn't running"
            : "Permission denied talking to the Docker daemon",
    );
    if (state === "no-cli") {
      const method = process.stdin.isTTY && !out.isJson() ? dockerInstallMethod() : "none";
      if (method !== "none") {
        const ready = await offerDockerInstall(out, method);
        if (ready) continue;
        for (const line of dockerFixHint(state)) out.log(dim(`  ${line}`));
        return false;
      }
      for (const line of dockerFixHint(state)) out.log(dim(`  ${line}`));
      out.log(dim("  Or point --statewave-url at an already-running server."));
      return false;
    }
    for (const line of dockerFixHint(state)) out.log(dim(`  ${line}`));
    if (state !== "daemon-down" || !process.stdin.isTTY || out.isJson()) {
      out.log(dim("  Or point --statewave-url at an already-running server."));
      return false;
    }
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const ans = (
      await new Promise<string>((res) =>
        rl.question(`  ${dim("[Enter = retry, 'o' = open Docker Desktop & retry, 'x' = exit]")}: `, res),
      )
    )
      .trim()
      .toLowerCase();
    rl.close();
    if (ans === "x") return false;
    if (ans === "o" && process.platform === "darwin") {
      try {
        execFileSync("open", ["-a", "Docker"], { stdio: "ignore" });
        out.log(dim("  Opening Docker Desktop… giving it a moment before retrying."));
      } catch {
        // open failed — fall through to a plain retry
      }
    }
    await new Promise((r) => setTimeout(r, ans === "o" ? 8000 : 1500));
  }
}

/** First absolute path for `bin` on the PATH, or undefined. Cross-platform. */
function resolveOnPath(bin: string): string | undefined {
  const sep = process.platform === "win32" ? ";" : ":";
  const names = process.platform === "win32" ? [`${bin}.exe`, `${bin}.cmd`, bin] : [bin];
  for (const d of (process.env.PATH ?? "").split(sep)) {
    if (!d) continue;
    for (const n of names) {
      const p = join(d, n);
      if (existsSync(p)) return p;
    }
  }
  return undefined;
}

function onPath(bin: string): boolean {
  return resolveOnPath(bin) !== undefined;
}

// Best-effort "is this client installed?" — a config dir, an app bundle, or the
// binary on PATH. Used to pick sensible defaults; --client / --all always win.
const CLIENT_DETECT: Record<string, () => boolean> = {
  "claude-desktop": () =>
    existsSync(resolve(homedir(), "Library/Application Support/Claude")) ||
    existsSync(resolve(homedir(), ".config/Claude")) ||
    (!!process.env.APPDATA && existsSync(join(process.env.APPDATA, "Claude"))),
  claude: () => existsSync(resolve(homedir(), ".claude")) || onPath("claude"),
  cursor: () =>
    existsSync("/Applications/Cursor.app") ||
    existsSync(resolve(homedir(), ".cursor")) ||
    onPath("cursor"),
  vscode: () =>
    existsSync("/Applications/Visual Studio Code.app") ||
    existsSync(resolve(homedir(), ".vscode")) ||
    onPath("code"),
  codex: () => onPath("codex"),
};

/** Client ids that look installed on this machine, in registry order. */
export function detectClients(): string[] {
  return CLIENTS.map((c) => c.id).filter((id) => CLIENT_DETECT[id]?.() ?? false);
}

type Parsed<T> = { ok: true; value: T } | { ok: false; message: string };
const ok = <T,>(value: T): Parsed<T> => ({ ok: true, value });
const bad = (message: string): Parsed<never> => ({ ok: false, message });

/**
 * Render a prompt input line legibly on BOTH light and dark terminals. The fix
 * for "the hints are washed out": never `dim` text the user must read to answer.
 * A cyan marker (a mid-tone that stays visible on either background) anchors the
 * eye; the hint itself is the terminal's default foreground, which the terminal
 * already contrasts correctly against its own theme. We don't try to detect the
 * background — there's no reliable cross-terminal way — so theme-agnostic styling
 * (default fg + a safe accent, never dim, never a hardcoded light/dark colour) is
 * the robust choice.
 */
function promptText(hint: string): string {
  return `  ${cyan("›")} ${hint}: `;
}

/** A section question header: a cyan `?` marker + bold text — colourful and
 *  legible on light and dark terminals (bold uses the theme's own foreground). */
function questionHeader(text: string): string {
  return `${cyan("?")} ${bold(text)}`;
}

/**
 * Ask until `parse` accepts the answer. On anything invalid it re-prompts with a
 * hint instead of silently proceeding to a fallback — a mistyped choice should
 * never quietly pick the wrong thing. Ctrl-C still aborts the whole run.
 */
export async function askValid<T>(
  out: Output,
  ask: (q: string) => Promise<string>,
  question: string,
  parse: (answer: string) => Parsed<T>,
): Promise<T> {
  for (;;) {
    const r = parse(await ask(question));
    if (r.ok) return r.value;
    out.log(`  ${yellow("!")} ${r.message}`);
  }
}

/** Required API-key prompt: re-asks when blank, with an explicit 'offline' escape. */
async function askApiKey(out: Output, ask: (q: string) => Promise<string>): Promise<string | undefined> {
  const key = await askValid<string | undefined>(
    out,
    ask,
    promptText("API key (never written to config or printed; type 'offline' to cancel)"),
    (a) => {
      const t = a.trim();
      if (t.toLowerCase() === "offline") return ok<string | undefined>(undefined);
      if (t) return ok<string | undefined>(t);
      return bad("enter the API key, or type 'offline' to use local/offline instead.");
    },
  );
  if (!key) out.warn("using local/offline.");
  return key;
}

/**
 * Interactive memory-engine selection: offline (heuristic + keyword) or an LLM
 * provider via LiteLLM. Returns a ProviderConfig, or null for offline. Only runs
 * on a TTY; the API key is read inline but never echoed back in any summary.
 * Every constrained prompt re-asks on invalid input rather than falling through.
 */
async function promptMemoryEngine(out: Output): Promise<ProviderConfig | null> {
  if (!process.stdin.isTTY) return null;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> => new Promise((res) => rl.question(q, res));
  try {
    out.log("");
    out.log(questionHeader("How should Statewave build and search memory?"));
    out.log(`  ${cyan("1")}. ${bold("Configure an LLM provider")} ${green("(recommended)")} — cleaner fact extraction + semantic retrieval (LiteLLM).`);
    out.log(`  ${cyan("2")}. Local / offline — built-in heuristic compiler + keyword retrieval. No key, no cost.`);
    const mode = await askValid(out, ask, promptText("1 = LLM provider (recommended) · 2 = local/offline · Enter = 1"), (a) => {
      const t = a.trim();
      if (t === "" || t === "1") return ok("llm" as const);
      if (t === "2") return ok("offline" as const);
      return bad("enter 1, 2, or just press Enter.");
    });
    if (mode === "offline") return null;

    out.log("");
    out.log(questionHeader("Choose a provider") + dim("  (via LiteLLM — not just OpenAI)"));
    PROVIDERS.forEach((p, i) => out.log(`  ${cyan(String(i + 1))}. ${p.label}`));
    const provider = await askValid(out, ask, promptText(`number 1–${PROVIDERS.length}`), (a) => {
      const n = Number.parseInt(a.trim(), 10);
      if (Number.isInteger(n) && n >= 1 && n <= PROVIDERS.length) return ok(PROVIDERS[n - 1]!);
      return bad(`enter a number from 1 to ${PROVIDERS.length}.`);
    });

    // Freeform LiteLLM id — no live list to offer, so just take a model + key.
    if (provider.id === "custom") {
      const model = await askValid(out, ask, promptText("Model (LiteLLM id, e.g. anthropic/claude-3-5-haiku-latest)"), (a) =>
        a.trim() ? ok(a.trim()) : bad("enter a LiteLLM model id."),
      );
      const apiKey = await askApiKey(out, ask);
      if (!apiKey) return null;
      return { provider: provider.id, model, apiKey };
    }

    // Credentials FIRST — needed to ask the provider what it currently serves.
    let apiBase: string | undefined;
    if (provider.needsApiBase) {
      const baseHint = provider.defaultApiBase ? `[Enter = ${provider.defaultApiBase}]` : "(required)";
      apiBase = await askValid(out, ask, promptText(`API base URL ${baseHint}`), (a) => {
        const t = a.trim() || provider.defaultApiBase;
        return t ? ok(t) : bad("an API base URL is required for this provider.");
      });
    }
    // Credentials + live model discovery in one step: the model fetch doubles as
    // a key check. A rejected key (wrong / expired) re-asks rather than wiring up
    // a server that can't authenticate; a network failure can't verify the key,
    // so we proceed with a warning and the built-in default. Listing live also
    // means a deprecated model is never offered as "best" (offline stays
    // first-class via the fallback).
    let apiKey: string | undefined;
    let catalog: ModelCatalog;
    for (;;) {
      if (provider.needsApiKey) {
        apiKey = await askApiKey(out, ask);
        if (!apiKey) return null;
      }
      out.log(dim(`  ${provider.needsApiKey ? "Checking your key and fetching" : "Fetching"} models from ${provider.label}…`));
      catalog = await listProviderModels(provider, { apiKey, apiBase });
      if (catalog.reason === "auth" && provider.needsApiKey) {
        out.warn(`${provider.label} rejected that key (${catalog.note ?? "unauthorized"}). It may be wrong or expired — try again, or type 'offline'.`);
        continue;
      }
      if (catalog.reason === "network") {
        out.warn(`couldn't verify the key with ${provider.label} (${catalog.note ?? "network error"}); proceeding — the server will use it as given.`);
      }
      break;
    }
    let model: string;
    if (catalog.source === "live" && catalog.models.length > 0 && catalog.recommended) {
      const shown = catalog.models.slice(0, 8);
      out.log(`  ${bold("Latest models")} ${dim("(recommended first)")}`);
      shown.forEach((m, i) =>
        out.log(`    ${cyan(String(i + 1))}. ${m}${m === catalog.recommended ? ` ${green("(recommended)")}` : ""}`),
      );
      model = await askValid(out, ask, promptText(`Enter = ${catalog.recommended}, or a number / model id`), (a) => {
        const t = a.trim();
        if (/^\d+$/.test(t)) {
          const n = Number.parseInt(t, 10);
          if (n < 1 || n > shown.length) return bad(`pick a number from 1 to ${shown.length}, or type a model id.`);
        }
        return ok(resolveModelAnswer(t, shown, catalog.recommended!));
      });
    } else {
      if (catalog.note) out.log(dim(`  ${catalog.note} — using the built-in default.`));
      const usableDefault = provider.defaultModel && !provider.defaultModel.includes("<") ? provider.defaultModel : "";
      model = await askValid(out, ask, promptText(`Model ${usableDefault ? `[Enter = ${usableDefault}]` : "(LiteLLM model id)"}`), (a) => {
        const t = a.trim() || usableDefault;
        return t ? ok(t) : bad("enter a LiteLLM model id.");
      });
    }

    let embeddingModel: string | undefined;
    if (!provider.defaultEmbeddingModel) {
      out.log(dim(`  ${provider.label} has no default embedding model — retrieval uses keywords unless you add one.`));
      embeddingModel = (await ask(promptText("Embedding model [Enter = keyword retrieval]"))).trim() || undefined;
    }

    return { provider: provider.id, model, apiKey, apiBase, embeddingModel };
  } finally {
    rl.close();
  }
}

/**
 * Parse a client-selection answer into the chosen clients. Pure, so it's unit
 * tested directly. Empty (just Enter) selects the detected set (or all when
 * nothing detected); `a`/`all` selects everything from `list`; `n`/`none`
 * selects nothing; otherwise 1-based indices into `list` (`1,3` / `1 3`).
 * `list` defaults to the full registry for backward compatibility.
 */
export function parseClientSelection(answer: string, detected: ReadonlyArray<ClientDef>, list: ReadonlyArray<ClientDef> = CLIENTS): ClientDef[] {
  const t = answer.trim().toLowerCase();
  if (t === "") return detected.length ? [...detected] : [...list];
  if (t === "a" || t === "all") return [...list];
  if (t === "n" || t === "none") return [];
  const nums = t
    .split(/[\s,]+/)
    .map((x) => Number.parseInt(x, 10))
    .filter((n) => Number.isInteger(n) && n >= 1 && n <= list.length);
  return [...new Set(nums)].map((n) => list[n - 1]!);
}

/** Interactively show only the detected clients and let the user pick a subset. */
async function promptClientSelection(out: Output, detectedIds: Set<string>): Promise<ClientDef[]> {
  const detected = CLIENTS.filter((c) => detectedIds.has(c.id));
  // If nothing is detected, fall back to showing the full registry so the user
  // can still pick manually.
  const list = detected.length ? detected : CLIENTS;
  out.log("");
  out.log(questionHeader("Which MCP clients should I set up?"));
  list.forEach((c, i) => {
    const suffix = list === CLIENTS ? ` ${gray("not detected")}` : "";
    out.log(`  ${cyan(String(i + 1))}. ${c.label}${suffix}`);
  });
  const hint = `Enter = ${list === CLIENTS ? "all" : "detected"}, e.g. 1,2 = pick, 'n' = none`;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> => new Promise((res) => rl.question(q, res));
  try {
    return await askValid(out, ask, promptText(hint), (answer) => {
      const t = answer.trim().toLowerCase();
      const chosen = parseClientSelection(answer, list, list);
      if (chosen.length === 0 && t !== "" && t !== "n" && t !== "none") {
        return bad(`didn't recognize "${answer.trim()}" — enter Enter, n, or numbers like 1,2.`);
      }
      return ok(chosen);
    });
  } finally {
    rl.close();
  }
}

// The Statewave IDE Companion — the *capture* half: it auto-ingests your file
// and git activity into Statewave as you work. Complements the MCP config,
// which only lets the assistant *read* memory. Cross-platform resolution +
// verified install live in ./extensions.ts (EXTENSION_ID, installAndVerify,
// isEditorClient), unit-tested across the full 8-case matrix.

export type QuickstartSeverity = "ok" | "warning" | "error";

/**
 * The run's overall outcome, kept as one small honest rule so the headline and
 * exit code can never disagree. A FAILURE is a requested action that did not
 * complete (a selected repo did not seed) → severity "error", exit 1. A WARNING
 * is advisory (the optional IDE Companion) → severity "warning", exit 0. Server
 * and client-config failures exit earlier and never reach here.
 */
export function quickstartOutcome(
  seedResults: ReadonlyArray<{ ok: boolean }>,
  warningCount: number,
): { severity: QuickstartSeverity; exitCode: 0 | 1; failedSeeds: number } {
  const failedSeeds = seedResults.filter((r) => !r.ok).length;
  if (failedSeeds > 0) return { severity: "error", exitCode: 1, failedSeeds };
  if (warningCount > 0) return { severity: "warning", exitCode: 0, failedSeeds: 0 };
  return { severity: "ok", exitCode: 0, failedSeeds: 0 };
}

/**
 * Verified episode count for a subject, read from `/v1/timeline` — which reads
 * the episodes table directly. We deliberately do NOT use `/v1/subjects`: it's a
 * lagging aggregate that can report 0 right after a write (confirmed against the
 * live server), so trusting it would produce false "seeding failed" results.
 * Returns null on any error. Memory count is intentionally omitted — compilation
 * is asynchronous, so it isn't reliably non-zero immediately after seeding.
 */
export async function subjectCounts(
  baseUrl: string,
  subject: string,
  fetchImpl: typeof fetch = fetch,
): Promise<{ episodes: number } | null> {
  try {
    const url = `${baseUrl.replace(/\/+$/, "")}/v1/timeline?subject_id=${encodeURIComponent(subject)}&limit=1000`;
    const res = await fetchImpl(url);
    if (!res.ok) return null;
    const data = (await res.json()) as { episodes?: unknown[] };
    return Array.isArray(data.episodes) ? { episodes: data.episodes.length } : null;
  } catch {
    return null;
  }
}

/** Parse a 1-based multi-select over `count` discovered repos. Pure (tested). */
export function parseRepoSelection(answer: string, count: number): number[] {
  const t = answer.trim().toLowerCase();
  if (t === "" || t === "a" || t === "all") return Array.from({ length: count }, (_, i) => i);
  if (t === "n" || t === "none") return [];
  const nums = t
    .split(/[\s,]+/)
    .map((x) => Number.parseInt(x, 10))
    .filter((n) => Number.isInteger(n) && n >= 1 && n <= count);
  return [...new Set(nums)].map((n) => n - 1);
}

function showRepoList(out: Output, repos: RepoIdentity[]): void {
  repos.forEach((r, i) => {
    out.log(`  ${cyan(String(i + 1))}. ${bold(r.subject)}${gray(`  ${r.root}`)}${r.fromRemote ? "" : dim("  (no remote)")}`);
  });
}

async function ask(rl: ReturnType<typeof createInterface>, q: string): Promise<string> {
  return (await new Promise<string>((res) => rl.question(q, res))).trim();
}

/** Render discovered repos and parse a multi-select. Assumes repos.length > 0. */
async function pickFromRepos(
  out: Output,
  rl: ReturnType<typeof createInterface>,
  repos: RepoIdentity[],
  truncated: boolean,
  root: string,
): Promise<RepoIdentity[]> {
  out.log("");
  out.log(`Found ${repos.length}${truncated ? "+ (truncated)" : ""} repositories under ${root}:`);
  showRepoList(out, repos);
  const sel = parseRepoSelection(
    await ask(rl, promptText("Enter/a = all, e.g. 1,3 = pick, n = none")),
    repos.length,
  );
  return sel.map((i) => repos[i]!);
}

/** Discover under a root, then let the user multi-select (used by --discover). */
async function discoverAndPick(out: Output, root: string): Promise<RepoIdentity[]> {
  const resolved = resolve(root);
  const { repos, truncated } = discoverRepos(resolved);
  if (repos.length === 0) {
    out.warn(`No git repositories found under ${resolved} — nothing to seed.`);
    return [];
  }
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    return await pickFromRepos(out, rl, repos, truncated, resolved);
  } finally {
    rl.close();
  }
}

/** Expand a leading `~` and resolve to an absolute path. */
export function expandUserPath(p: string): string {
  return resolve(p.replace(/^~(?=$|\/)/, homedir()));
}

/** A typed answer that looks like a filesystem path (absolute, ~, ./, or C:\). */
export function looksLikePath(s: string): boolean {
  return /^[~./]/.test(s) || /^[A-Za-z]:[\\/]/.test(s);
}

/** A typed answer that looks like a remote repository URL (https/http/git/ssh). */
export function looksLikeUrl(s: string): boolean {
  return /^https?:\/\/|^git@|^git:\/\/|^ssh:\/\//.test(s);
}

/** Interactive repository selection: current repo, discover, path, or skip. */
async function promptRepoSelection(out: Output, identity: RepoIdentity | undefined): Promise<RepoIdentity[]> {
  out.log("");
  out.log(questionHeader("Which repositories should Statewave seed?"));
  let n = 0;
  const opts: Array<"current" | "discover" | "path" | "skip"> = [];
  if (identity) {
    out.log(`  ${cyan(String(++n))}. Current repository  ${gray(identity.root)}  → ${bold(identity.subject)}`);
    opts.push("current");
  }
  out.log(`  ${cyan(String(++n))}. Discover repositories under a folder`);
  opts.push("discover");
  out.log(`  ${cyan(String(++n))}. Enter a local repository path`);
  opts.push("path");
  out.log(`  ${cyan(String(++n))}. Skip seeding`);
  opts.push("skip");

  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const def = identity ? "current" : "discover";
  try {
    // Loop until the user picks repos or EXPLICITLY skips — never silently skip
    // on unrecognized input. A path typed here (the natural thing to do at this
    // prompt) is DWIM'd: a git repo → use it; a folder → discover under it.
    for (;;) {
      const raw = await ask(rl, promptText(`Enter = ${def === "current" ? "current repo" : "discover"}, a number, or a path`));

      if (raw && looksLikeUrl(raw)) {
        out.log(`  ${yellow("!")} Statewave seeds from a local clone, not a remote URL.`);
        out.log(`  ${dim("Clone it first:")}  git clone ${raw} ~/your-path`);
        out.log(`  ${dim("Then enter that local path here, or press Enter to use the current repo.")}`);
        continue;
      }

      if (raw && looksLikePath(raw)) {
        const target = expandUserPath(raw);
        const repo = resolveRepoIdentity(target);
        if (repo) return [repo];
        const { repos, truncated } = discoverRepos(target);
        if (repos.length > 0) {
          const picked = await pickFromRepos(out, rl, repos, truncated, target);
          if (picked.length) return picked;
          return []; // found repos, user picked none → an explicit skip
        }
        out.log(
          `  ${yellow("!")} ${existsSync(target) ? `no git repositories under ${target}` : `${target} doesn't exist`}` +
            ` — enter a different path, a number, or 'n' to skip.`,
        );
        continue;
      }

      const lc = raw.toLowerCase();
      const choice: "current" | "discover" | "path" | "skip" | undefined =
        raw === ""
          ? def
          : lc === "n" || lc === "none" || lc === "skip"
            ? "skip"
            : (() => {
                const num = Number.parseInt(raw, 10);
                return Number.isInteger(num) && num >= 1 && num <= opts.length ? opts[num - 1] : undefined;
              })();

      if (!choice) {
        out.log(`  ${yellow("!")} enter a number from 1 to ${opts.length}, a path, or 'n' to skip.`);
        continue;
      }

      switch (choice) {
        case "current":
          return identity ? [identity] : [];
        case "skip":
          return [];
        case "discover": {
          const folder = (await ask(rl, promptText(`Folder to search [Enter = ${process.cwd()}]`))) || process.cwd();
          const root = expandUserPath(folder);
          const { repos, truncated } = discoverRepos(root);
          if (repos.length === 0) {
            out.log(`  ${yellow("!")} no git repositories under ${root} — enter a different folder, a number, or 'n' to skip.`);
            continue;
          }
          const picked = await pickFromRepos(out, rl, repos, truncated, root);
          if (picked.length) return picked;
          return [];
        }
        case "path": {
          const p = await ask(rl, promptText("Local path to repository (e.g. ~/projects/my-app)"));
          if (p && looksLikeUrl(p)) {
            out.log(`  ${yellow("!")} That looks like a URL — Statewave needs a local clone.`);
            out.log(`  ${dim("Run:")}  git clone ${p} ~/your-path  ${dim("then enter that path.")}`);
            continue;
          }
          const id = p ? resolveRepoIdentity(expandUserPath(p)) : undefined;
          if (id) return [id];
          out.log(`  ${yellow("!")} ${p || "(empty)"} is not a git repository — enter a path, a number, or 'n' to skip.`);
          continue;
        }
      }
    }
  } finally {
    rl.close();
  }
}

/** Resolve the repositories to seed from flags or interaction. */
async function selectRepos(
  out: Output,
  args: ParsedArgs,
  identity: RepoIdentity | undefined,
  explicitSubject: string | undefined,
): Promise<RepoIdentity[]> {
  if (explicitSubject) {
    return [{ root: identity?.root ?? process.cwd(), subject: explicitSubject, fromRemote: identity?.fromRemote ?? false }];
  }
  const reposFlag = flagAsString(args, "repos");
  if (reposFlag) {
    return reposFlag
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
      .map((p) => resolveRepoIdentity(resolve(p)))
      .filter((r): r is RepoIdentity => Boolean(r));
  }
  const discoverRoot = flagAsString(args, "discover");
  if (discoverRoot) {
    if (process.stdin.isTTY && !out.isJson() && !flagAsBool(args, "yes")) return discoverAndPick(out, discoverRoot);
    return discoverRepos(resolve(discoverRoot)).repos;
  }
  if (process.stdin.isTTY && !out.isJson() && !flagAsBool(args, "yes")) {
    return promptRepoSelection(out, identity);
  }
  return identity ? [identity] : [];
}

/**
 * Client-specific "test it here" steps with the correct reload behavior:
 * CLI clients need a new terminal; editors need a window reload; the chat app
 * needs a full restart and picks the subject in-app.
 */
function clientTestSteps(client: ClientDef, root: string, subject: string): string[] {
  const ask = `Ask: ${cyan(`"What changed recently in this repository?"`)}`;
  switch (client.id) {
    case "claude":
      // Claude Code is the CLI OR the IDE extension. Only tell the user to run
      // `claude` if it's actually on PATH — otherwise point at the extension
      // (which also auto-reads .mcp.json) so we never suggest a missing command.
      return onPath("claude")
        ? [`Open a terminal in ${root} and run \`claude\`.`, ask]
        : [
            `Open ${root} in your IDE and use the Claude Code extension — it auto-reads .mcp.json (reload the window if it was already open).`,
            `Prefer the CLI? Install it with \`npm i -g @anthropic-ai/claude-code\`, then run \`claude\` in ${root}.`,
            ask,
          ];
    case "codex":
      return onPath("codex")
        ? [`Open a terminal in ${root} and run \`codex\`.`, ask]
        : [
            `The \`codex\` CLI isn't on your PATH. Install the Codex CLI, then run \`codex\` in ${root} (its config is already written).`,
            ask,
          ];
    case "cursor":
      return [`Open ${root} in Cursor (reload the window if it was already open), then open Agent chat.`, ask];
    case "vscode":
      return [`Open ${root} in VS Code (reload the window), then open Copilot Chat in Agent mode.`, ask];
    case "claude-desktop":
      return [
        "Quit and reopen Claude Desktop, then start a new chat.",
        `Ask it to list available repository subjects and pick ${bold(subject)}.`,
      ];
    default:
      return [`Open ${client.label} and ask it about subject ${subject}.`];
  }
}

/**
 * Per-client "here's what you can do now" block shown at the end of quickstart.
 * For file-based clients, explains that it's ready and gives a first question.
 * For Claude Desktop, shows the paste block inline so the user doesn't have to
 * open a file for that one-time step.
 */
function clientUsageBlock(client: ClientDef, root: string, subject: string, pasteBlock?: string): string[] {
  switch (client.id) {
    case "claude":
      return [
        dim("CLAUDE.md written — context loads automatically every session."),
        onPath("claude")
          ? `Open a terminal in ${root} and run \`claude\`.`
          : `Open ${root} in your IDE with the Claude Code extension (reload window).`,
        `Try: ${cyan('"What decisions has this project made, and why?"')}`,
      ];
    case "cursor":
      return [
        dim("AGENTS.md written — context loads automatically in Agent mode."),
        `Open ${root} in Cursor, then open Agent chat ${dim("(Cmd+L → Agent)")} and try:`,
        `  ${cyan('"What changed recently in this repo and why?"')}`,
      ];
    case "vscode":
      return [
        dim("copilot-instructions.md written — Copilot reads it in Agent mode automatically."),
        `Open ${root} in VS Code, then Copilot Chat → Agent mode and try:`,
        `  ${cyan('"What does this codebase prioritize?"')}`,
      ];
    case "codex":
      return [
        dim("AGENTS.md written — context loads automatically."),
        `Run \`codex\` in ${root} and try:`,
        `  ${cyan('"What patterns does this project follow?"')}`,
      ];
    case "claude-desktop": {
      const lines: string[] = [
        `${yellow("One-time step:")} paste your memory instructions into Custom Instructions.`,
        `  ${bold("Settings → Custom Instructions")} — paste the block below:`,
        "",
      ];
      if (pasteBlock) {
        for (const line of pasteBlock.trim().split("\n")) lines.push(`  ${dim(line)}`);
        lines.push("");
      }
      lines.push(`Quit and reopen Claude Desktop, then start a new chat and ask:`);
      lines.push(`  ${cyan('"What Statewave subjects do I have?"')}`);
      lines.push(dim(`  (or: "Summarize ${subject}.")`));
      return lines;
    }
    default:
      return [`Open ${client.label} and ask about ${bold(subject)}.`];
  }
}

export async function runQuickstart(args: ParsedArgs): Promise<number> {
  const out = new Output({ json: flagAsBool(args, "json") });
  const cwd = process.cwd();
  const apiPort = flagAsInt(args, "api-port") ?? 8100;
  const adminPort = flagAsInt(args, "admin-port") ?? 8080;
  const includeAdmin = !flagAsBool(args, "no-admin");
  const doSeed = !flagAsBool(args, "no-seed");
  const baseUrl = flagAsString(args, "statewave-url") ?? `http://localhost:${apiPort}`;
  // Subject comes from real git identity (remote → repo:owner/name, else the
  // work-tree basename), NOT the cwd name. Undefined when this isn't a repo and
  // no explicit --subject was given — we then skip seeding rather than invent a
  // bogus subject like `repo:<home-dir>`.
  const identity = resolveRepoIdentity(cwd);
  const subject = flagAsString(args, "subject") ?? identity?.subject;
  // Optional-stage warnings; the final summary and exit reflect them honestly.
  const warnings: string[] = [];

  if (flagAsBool(args, "down")) {
    if (!existsSync(COMPOSE_PATH)) {
      out.log("No quickstart stack found — nothing to stop.");
      return 0;
    }
    const downArgs = ["compose", "-p", PROJECT_NAME, "-f", COMPOSE_PATH, "down"];
    if (flagAsBool(args, "purge")) downArgs.push("--volumes");
    try {
      execFileSync("docker", downArgs, { stdio: "inherit" });
      out.log("Quickstart stack stopped.");
      return 0;
    } catch (err) {
      out.error(`docker compose down failed: ${(err as Error).message}`);
      return 1;
    }
  }

  // Welcome banner — the first thing a normal run shows (skipped in --json so
  // machine output stays clean). Sets context for the prompts that follow.
  if (!out.isJson()) {
    out.log("");
    out.log(`${bold("Welcome to Statewave")} ${dim("— a local memory layer for your AI tools.")}`);
    out.log(dim("One command: start a server, wire your MCP clients, and seed your repos — all on your machine."));
  }

  // Environment preflight (informational): Node already runs this code; Git is
  // needed for repo identity + seeding. Docker is checked lazily, only if we
  // actually need to start a server.
  if (!nodeMeetsMinimum(process.version)) {
    out.warn(`Node ${process.version} is below the supported minimum (>= ${MIN_NODE_MAJOR}); some steps may misbehave.`);
  }
  if (!gitAvailable()) {
    out.warn("git not found on PATH — repository detection and seeding will be skipped.");
  }

  // Docker preflight — surface a missing install before any interactive prompts
  // so the user doesn't answer several questions only to hit a hard stop.
  // Skip when reusing an external server (--statewave-url).
  let serverAlreadyUp = false;
  if (!flagAsString(args, "statewave-url")) {
    serverAlreadyUp = await checkHealth(baseUrl);
    if (serverAlreadyUp) {
      if (!out.isJson()) out.log(`\n${green("✓")} Statewave server already running at ${baseUrl} — reusing it.`);
    } else if (!(await ensureDockerReady(out))) return 1;
  }

  // Which clients to configure: explicit --client a,b,c | --all | interactive pick | auto-detect.
  let clients: ClientDef[];
  {
    const explicit = flagAsString(args, "client");
    if (explicit) {
      const resolved: ClientDef[] = [];
      for (const id of explicit.split(",").map((s) => s.trim()).filter(Boolean)) {
        const c = findClient(id);
        if (!c) {
          out.error(`unknown client: ${id}`, `supported: ${CLIENTS.map((x) => x.id).join(", ")}`);
          return 2;
        }
        resolved.push(c);
      }
      clients = resolved;
    } else if (flagAsBool(args, "all")) {
      clients = CLIENTS.slice();
    } else {
      const detectedIds = new Set(detectClients());
      const detected = CLIENTS.filter((c) => detectedIds.has(c.id));
      const interactive = !!process.stdin.isTTY && !out.isJson();
      const assumeYes = flagAsBool(args, "yes") || flagAsBool(args, "y");
      if (interactive && !assumeYes) {
        clients = await promptClientSelection(out, detectedIds);
      } else if (detected.length) {
        clients = detected;
        out.log(dim(`Configuring detected clients: ${detected.map((c) => c.id).join(", ")} (--client to narrow).`));
      } else {
        clients = [findClient("claude-desktop")!];
        out.log(dim("No MCP clients detected — defaulting to Claude Desktop (use --client/--all)."));
      }
    }
  }
  if (clients.length === 0) {
    out.log(dim("No clients selected — starting/seeding the server but configuring nothing."));
  }

  // Memory engine: offline heuristic by default, or an LLM provider via LiteLLM.
  // Provider config only matters when WE start the server (a reused server is
  // already configured). Resolve flag/env config up front to warn on reuse.
  const forceOffline = flagAsBool(args, "no-llm");
  const flagKey = forceOffline
    ? undefined
    : flagAsString(args, "llm-api-key") ??
      process.env.STATEWAVE_LITELLM_API_KEY ??
      process.env.OPENAI_API_KEY;
  const flagProvider = forceOffline ? undefined : flagAsString(args, "provider");
  let providerConfig: ProviderConfig | undefined =
    !forceOffline && (flagProvider || flagKey)
      ? {
          provider: flagProvider ?? "openai",
          model: flagAsString(args, "llm-model"),
          apiKey: flagKey,
          apiBase: flagAsString(args, "api-base"),
          embeddingModel: flagAsString(args, "embedding-model"),
        }
      : undefined;

  // 1. Server — reuse an existing healthy one, otherwise bring up the stack.
  //    Docker was already verified ready in the preflight above (when managing
  //    our own stack), so we don't call ensureDockerReady again here.
  let startedStack = false;
  if (serverAlreadyUp || await checkHealth(baseUrl)) {
    // serverAlreadyUp case: already announced before the client prompt.
    // --statewave-url case: announce here (first time we know the server is reachable).
    if (!serverAlreadyUp) {
      out.log(`${green("✓")} Statewave server reachable at ${baseUrl} — reusing it.`);
    }
    if (providerConfig) {
      out.warn(
        "an LLM provider was configured, but quickstart is reusing an already-running server — " +
          "it has no effect here; configure the provider on that server instead",
      );
    }
  } else {
    // Choose the memory engine before starting (interactive when none was given).
    if (!providerConfig && !forceOffline && !flagAsBool(args, "no-llm-prompt") && !out.isJson()) {
      providerConfig = (await promptMemoryEngine(out)) ?? undefined;
    }
    const llmEnvVars = providerConfig ? buildProviderEnv(providerConfig) : {};
    const memoryLabel = providerConfig
      ? `LLM compiler via ${providerConfig.provider}${
          llmEnvVars.STATEWAVE_EMBEDDING_PROVIDER === "litellm"
            ? " + semantic embeddings"
            : " + keyword retrieval (provider has no embeddings)"
        }`
      : "offline heuristic compiler + keyword retrieval (no key, no cost)";
    out.log("");
    out.log(bold(`Starting Statewave (api${includeAdmin ? " + admin" : ""} + db) via docker compose…`));
    out.log(`  memory: ${memoryLabel}`);
    await mkdir(STATE_DIR, { recursive: true });
    await writeFile(COMPOSE_PATH, renderComposeFile({ apiPort, adminPort, includeAdmin }), "utf8");
    try {
      execFileSync("docker", ["compose", "-p", PROJECT_NAME, "-f", COMPOSE_PATH, "up", "-d", "--pull", "always"], {
        stdio: "inherit",
        // Pass the provider env to compose; the compose file interpolates these
        // so the API key never lands on disk.
        env: { ...process.env, ...llmEnvVars },
      });
    } catch (err) {
      out.error(`docker compose up failed: ${(err as Error).message}`);
      return 1;
    }
    const healthy = await withSpinner(
      "Waiting for the API to become healthy…",
      () => waitForHealth(baseUrl, { timeoutMs: 180_000, intervalMs: 2_000 }),
      { active: !out.isJson() },
    );
    if (!healthy) {
      out.error(
        `server did not become healthy at ${baseUrl} within 3 minutes`,
        `inspect logs: docker compose -p ${PROJECT_NAME} -f ${COMPOSE_PATH} logs api`,
      );
      return 1;
    }
    startedStack = true;
    out.log(`${green("✓")} Server healthy at ${baseUrl}.`);
  }

  // Select the repositories to set up (config + seed) BEFORE configuring clients,
  // so project-scoped clients are configured INSIDE each selected repository.
  const reposToSeed = doSeed ? await selectRepos(out, args, identity, flagAsString(args, "subject")) : [];

  // 2. Configure clients. Project-scoped clients (Claude Code, Cursor, VS Code)
  //    — and any client with a repo instruction file (Codex) — are written into
  //    each selected repository so opening any of them targets that repo's
  //    subject. Pure user-scoped chat apps (Claude Desktop) are configured once.
  const serverBin = resolveLocalServerBin();
  const spec = buildServerSpec({ statewaveUrl: baseUrl, serverBin });
  let pasteBlock: string | undefined;
  out.log("");
  const configTargets: Array<{ root: string; subject: string }> = reposToSeed.length
    ? reposToSeed.map((r) => ({ root: r.root, subject: r.subject }))
    : [{ root: identity?.root ?? cwd, subject: subject ?? "repo:workspace" }];
  const noSubjectAnywhere = reposToSeed.length === 0 && !subject;
  const newlyConfigured: ClientDef[] = [];
  const alreadyConfigured: ClientDef[] = [];
  for (const client of clients) {
    try {
      const perRepo = client.scope === "project" || Boolean(client.instructionFile);
      const targets = perRepo ? configTargets : configTargets.slice(0, 1);
      let lastPaste: string | undefined;
      let anyChanged = false;
      for (const t of targets) {
        const r = await writeInit(client, spec, t.subject, t.root, {
          skipInstructions: flagAsBool(args, "no-instructions") || noSubjectAnywhere,
        });
        if (r.pasteBlock) lastPaste = r.pasteBlock;
        if (r.applied.some((a) => a.action !== "skip")) anyChanged = true;
      }
      if (lastPaste) pasteBlock = lastPaste;
      if (anyChanged) {
        newlyConfigured.push(client);
        out.log(
          `${green("✓")} Configured ${bold(client.label)}${targets.length > 1 ? gray(` (${targets.length} repos)`) : ""}`,
        );
      } else {
        alreadyConfigured.push(client);
        out.log(`${dim("–")} ${bold(client.label)} already configured`);
      }
    } catch (err) {
      out.error(`failed to configure ${client.label}: ${(err as Error).message}`);
      return 1;
    }
  }

  // 2b. Install the IDE Companion (capture side) for any chosen editor. Picking
  //     VS Code / Cursor is the consent — no second prompt. Opt out with
  //     --no-install-extension. Failures are soft (don't fail the whole run).
  if (!flagAsBool(args, "no-install-extension")) {
    const editors = clients.filter((c) => isEditorClient(c.id));
    if (editors.length) out.log("");
    const vsix = flagAsString(args, "extension-vsix");
    const target = vsix ?? EXTENSION_ID;
    const handled = new Set<string>(); // resolved binaries — forks sharing a CLI are handled once
    for (const e of editors) {
      const r = installAndVerify(e.id, target, { vsixGiven: Boolean(vsix) });
      const via =
        r.via && !e.label.includes(r.via) && !r.via.includes(e.label) ? `${e.label} (${r.via})` : e.label;
      if (r.binary && handled.has(r.binary)) {
        out.log(dim(`  ${e.label}: same editor as a prior selection (${r.via}) — already handled.`));
        continue;
      }
      if (r.binary) handled.add(r.binary);
      switch (r.status) {
        case "no-cli":
          warnings.push(`${e.label}: editor CLI not found — IDE Companion not installed`);
          out.log(`  ${yellow("!")} ${e.label}: CLI not found — install "${EXTENSION_ID}" from its Extensions panel.`);
          break;
        case "already":
          out.log(`${green("✓")} IDE Companion already installed in ${bold(via)}`);
          break;
        case "installed":
        case "updated":
          out.log(`${green("✓")} IDE Companion ${r.status} and verified in ${bold(via)}`);
          break;
        case "failed":
          warnings.push(`IDE Companion install failed in ${via}`);
          out.log(`  ${red("✗")} IDE Companion install failed in ${bold(via)}: ${r.message}`);
          out.log(dim(`    Install manually: open ${e.label} → Extensions → search "${EXTENSION_ID}".`));
          break;
        case "unverified":
          warnings.push(`IDE Companion install in ${via} could not be verified`);
          out.log(`  ${yellow("!")} IDE Companion install reported success in ${bold(via)} but couldn't be verified — open its Extensions panel to confirm.`);
          break;
      }
    }
  }

  // 3. Repository selection + seeding (zero, one, or many). Counts are verified
  //    against the server, never trusted from the seed command's own output.
  interface SeedResult { subject: string; root: string; ok: boolean; episodes?: number }
  const seedResults: SeedResult[] = [];
  if (doSeed && reposToSeed.length === 0) {
    out.log("");
    out.log(dim("No repository selected — seeding skipped. Seed later: statewave-connectors mcp seed --write"));
  }
  for (const repo of reposToSeed) {
    out.log("");
    out.log(bold(`Seeding ${repo.subject}`) + dim(`  (${repo.root})`));
    const seedCode = await runMcpSeed({
      positional: ["mcp", "seed"],
      flags: { subject: repo.subject, write: true, "statewave-url": baseUrl, "repo-path": repo.root, quiet: true },
    });
    const counts = await subjectCounts(baseUrl, repo.subject);
    const ok = seedCode === 0 && !!counts && counts.episodes > 0;
    seedResults.push({ subject: repo.subject, root: repo.root, ok, episodes: counts?.episodes });
    // Rendered per-subject in the summary below; tracked as a hard failure (not a
    // soft warning) because seeding is an action the user explicitly asked for.
  }

  // 4. Honest summary. Two severities, kept distinct: a FAILURE is a requested
  //    action that didn't complete (a selected repo didn't seed) and drives a
  //    non-zero exit; a WARNING is advisory (the optional IDE Companion) and
  //    does not. The headline and exit code never overstate what happened.
  const seededOk = seedResults.filter((r) => r.ok);
  const outcome = quickstartOutcome(seedResults, warnings.length);
  out.log("");
  if (outcome.severity === "error") {
    out.log(
      bold(
        `Statewave quickstart completed with errors — ${outcome.failedSeeds} of ${seedResults.length} ` +
          `${seedResults.length === 1 ? "repository" : "repositories"} did not seed.`,
      ),
    );
  } else if (outcome.severity === "warning") {
    out.log(bold(`Statewave quickstart complete — ${warnings.length} warning${warnings.length === 1 ? "" : "s"}.`));
  } else {
    out.log(bold("Statewave quickstart complete."));
  }
  out.log(`  ${green("✓")} Server: ${baseUrl}`);
  if (includeAdmin) {
    out.log(`  ${green("✓")} Admin dashboard: ${cyan(`http://localhost:${adminPort}`)}`);
  }
  if (newlyConfigured.length) {
    out.log(`  ${green("✓")} Configured: ${newlyConfigured.map((c) => c.label).join(", ")}`);
  }
  if (alreadyConfigured.length) {
    out.log(`  ${dim("–")} Already configured: ${alreadyConfigured.map((c) => c.label).join(", ")}`);
  }
  if (doSeed && reposToSeed.length === 0) out.log(`  ${dim("–")} Seeding skipped (no repository selected)`);
  for (const r of seedResults) {
    out.log(
      r.ok
        ? `  ${green("✓")} ${r.subject} — ${r.episodes} episodes (verified)`
        : `  ${red("✗")} ${r.subject} — seeding failed (re-run: statewave-connectors mcp seed --subject ${r.subject} --repo-path ${r.root} --write)`,
    );
  }
  if (seededOk.length > 0 && includeAdmin) {
    out.log(`  ${dim("→")} Inspect seeded memory: ${cyan(`http://localhost:${adminPort}`)}`);
  }
  for (const w of warnings) out.log(`  ${yellow("!")} ${w}`);

  // Per-client: how to start using Statewave right now.
  const testRepo = seededOk[0] ?? configTargets[0];
  if (clients.length && testRepo) {
    out.log("");
    out.log(bold("Using Statewave"));
    out.log(dim("Your AI tools now have persistent memory of this codebase."));
    out.log(dim("Ask why code is the way it is, not just what it does."));
    for (const c of clients) {
      out.log("");
      const needsPaste = c.id === "claude-desktop" && pasteBlock;
      out.log(`  ${bold(c.label)}${needsPaste ? `  ${dim("← one-time paste needed")}` : ""}`);
      for (const line of clientUsageBlock(c, testRepo.root, testRepo.subject, needsPaste ? pasteBlock : undefined)) {
        out.log(`    ${line}`);
      }
    }
  }

  // Always save the Claude Desktop paste block to file as a fallback reference.
  if (pasteBlock) {
    const instrPath = resolve(STATE_DIR, "chat-instructions.md");
    try {
      await mkdir(STATE_DIR, { recursive: true });
      await writeFile(instrPath, pasteBlock.trimEnd() + "\n", "utf8");
    } catch {
      // non-fatal
    }
  }
  if (startedStack) {
    out.log("");
    out.log(dim("Stop the stack later with: statewave-connectors quickstart --down"));
  }
  // Partial success stays partial: a non-zero exit if any requested seed failed,
  // so scripts and CI can tell a clean run from one that needs a re-seed. Soft
  // warnings (optional IDE Companion) do not change the exit code.
  return outcome.exitCode;
}
